import axios, { AxiosRequestConfig } from "axios";

// 1. Create the base instance
/**
 * Pre-configured Axios instance for application-wide API requests.
 * Includes base URL from environment, content-type headers, and `withCredentials: true`
 * for automatic HttpOnly cookie handling.
 *
 * Interceptors handle global errors such as 401 Unauthorized.
 *
 * @example
 * ```ts
 * const data = await api.get("/users");
 * ```
 */
export const axiosInstance = axios.create({
  baseURL: process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000",
  headers: {
    "Content-Type": "application/json",
  },
  withCredentials: true,
});

// 2. Request Interceptor: Cleaned up
axiosInstance.interceptors.request.use(
  (config) => {
    // We no longer manually attach the Authorization header here.
    // The browser handles the HttpOnly cookie automatically.
    return config;
  },
  (error) => Promise.reject(error),
);

// 3. Response Interceptor: Global error handling
axiosInstance.interceptors.response.use(
  (response) => response,
  async (error) => {
    // Catch 401 Unauthorized globally (e.g., expired cookie)
    if (error.response?.status === 401) {
      // If you implement a rotating refresh token, this is where you
      // would intercept the 401, call your /api/refresh endpoint
      // (which automatically sends the HttpOnly refresh cookie),
      // and then retry the original request.
    }

    return Promise.reject(error);
  },
);

/**
 * Custom Axios API client for making HTTP requests with proper error handling.
 *
 * @param config - Axios request configuration
 * @param options - Axios request options (merged with base config)
 * @returns Promise with the API response data
 *
 * @example
 * ```ts
 * const response = await api<User[]>({ url: "/users" });
 * ```
 */
export const api = async <T = unknown>(
  config: AxiosRequestConfig,
  options?: AxiosRequestConfig, // <-- Add this second parameter
): Promise<T> => {
  // Merge the base config generated by Orval with any custom options (like headers)
  const response = await axiosInstance({
    ...config,
    ...options,
  });

  return response.data;
};
