import { Exam } from "@/types/exam";

export const mockExamsData: Record<"ar" | "en", Exam[]> = {
  ar: [
    {
      id: "exam-001",
      title: "امتحان شامل على التيار الكهربي وقانون أوم",
      description:
        "### امتحان نهائي شامل\n\nيغطي هذا الامتحان الوحدة الأولى من منهج الفيزياء وتشمل: **شدة التيار الكهربي**، **قانون أوم**، وتطبيقات الدائرة المغلقة.\n\n- الزمن: 45 دقيقة\n- درجة النجاح: 60%",
      subject: "physics",
      grade: "grade3",
      teacherName: "أ. محمد عبد المعبود",
      category: "final",
      examType: "course-dependent",
      courseId: "course-001",
      courseTitle: "الفيزياء للثانوية العامة - منهج الترم الأول كامل",
      triesAllowed: 1,
      durationMinutes: 45,
      passingPercentage: 60,
      showModelAnswers: true,
      randomizeQuestionsOrder: true,
      randomizeMCQChoices: false,
      examSections: [
        {
          id: "esec-001",
          title: "الجزء الأول: أسئلة اختيار من متعدد",
          questions: [
            {
              id: "q-001",
              questionName: "وحدة شدة التيار",
              questionContent: "ما هي وحدة قياس شدة التيار الكهربي في النظام الدولي؟",
              modelAnswer: "opt-1",
              type: "mcq",
              options: [
                { id: "opt-1", text: "أمبير (A)" },
                { id: "opt-2", text: "فولت (V)" },
                { id: "opt-3", text: "أوم (Ω)" },
                { id: "opt-4", text: "كولوم (C)" },
              ],
              grade: 5,
              required: true,
              questionType: "theoretical",
              difficulty: "easy",
              hasAnswerExplanation: true,
              answerExplanation: "الأمبير هو وحدة شدة التيار الكهربي ويساوي كولوم لكل ثانية.",
            },
            {
              id: "q-002",
              questionName: "تطبيق قانون أوم",
              questionContent:
                "دائرة كهربية مقاومتها 10 أوم وفرق الجهد عبرها 20 فولت، ما شدة التيار؟",
              modelAnswer: "opt-2",
              type: "mcq",
              options: [
                { id: "opt-1", text: "0.5 أمبير" },
                { id: "opt-2", text: "2 أمبير" },
                { id: "opt-3", text: "200 أمبير" },
                { id: "opt-4", text: "10 أمبير" },
              ],
              grade: 10,
              required: true,
              questionType: "application-based",
              difficulty: "medium",
              hasAnswerExplanation: false,
            },
          ],
        },
      ],
      numberOfQuestions: 15,
      numberOfStudents: 832,
      successRate: 74,
      timesUsed: 1250,
      publishStatus: "published",
      createdAt: "2026-08-01T10:00:00Z",
    },
    {
      id: "exam-002",
      title: "اختبار نصف الفصل - الكيمياء العضوية",
      description:
        "### اختبار منتصف الفصل\n\nيتناول هذا الاختبار وحدة الهيدروكربونات الأليفاتية (الألكانات، الألكينات، الألكاينات) وتسمية المركبات العضوية.",
      subject: "chemistry",
      grade: "grade3",
      teacherName: "د. إيهاب عبد العزيز",
      category: "midterm",
      examType: "course-dependent",
      courseId: "course-002",
      courseTitle: "الكيمياء العضوية والتفوق فيها",
      triesAllowed: 2,
      durationMinutes: 30,
      passingPercentage: 50,
      showModelAnswers: false,
      randomizeQuestionsOrder: true,
      randomizeMCQChoices: true,
      examSections: [
        {
          id: "esec-002",
          title: "تسمية المركبات",
          questions: [
            {
              id: "q-003",
              questionName: "تسمية الألكانات",
              questionContent: "ما الاسم الصحيح للمركب CH3-CH2-CH3 وفق نظام IUPAC؟",
              modelAnswer: "opt-1",
              type: "mcq",
              options: [
                { id: "opt-1", text: "بروبان" },
                { id: "opt-2", text: "إيثان" },
                { id: "opt-3", text: "بيوتان" },
                { id: "opt-4", text: "ميثان" },
              ],
              grade: 5,
              required: true,
              questionType: "theoretical",
              difficulty: "easy",
              hasAnswerExplanation: false,
            },
          ],
        },
      ],
      numberOfQuestions: 10,
      numberOfStudents: 510,
      successRate: 61,
      timesUsed: 680,
      publishStatus: "published",
      createdAt: "2026-08-05T09:00:00Z",
    },
    {
      id: "exam-003",
      title: "اختبار وحدة تشابه المثلثات والمضلعات",
      description:
        "### اختبار الوحدة الأولى\n\nيختبر هذا الاختبار مفهوم تشابه المضلعات والمثلثات وتطبيقات نظرية تاليس.",
      subject: "mathematics",
      grade: "grade1",
      teacherName: "أ. أحمد سرور",
      category: "unit",
      examType: "course-dependent",
      courseId: "course-003",
      courseTitle: "أساسيات الرياضيات والفرع الهندسي",
      triesAllowed: 1,
      durationMinutes: 40,
      passingPercentage: 55,
      showModelAnswers: true,
      randomizeQuestionsOrder: false,
      randomizeMCQChoices: false,
      examSections: [
        {
          id: "esec-003",
          title: "أسئلة التشابه",
          questions: [
            {
              id: "q-004",
              questionName: "نسبة التشابه",
              questionContent:
                "إذا كان المثلثان ABC و DEF متشابهان ونسبة التشابه 1:3، فما نسبة مساحتيهما؟",
              modelAnswer: "1:9",
              type: "text",
              grade: 10,
              required: true,
              questionType: "analytical",
              difficulty: "hard",
              hasAnswerExplanation: true,
              answerExplanation: "نسبة المساحتين = مربع نسبة التشابه = (1/3)² = 1/9",
            },
          ],
        },
      ],
      numberOfQuestions: 8,
      numberOfStudents: 1240,
      successRate: 58,
      timesUsed: 1950,
      publishStatus: "published",
      createdAt: "2026-07-20T08:00:00Z",
    },
    {
      id: "exam-004",
      title: "امتحان الأحياء - الوراثة والـ DNA",
      description:
        "### الوحدة الثانية: الوراثة الجزيئية\n\nيغطي الامتحان التركيب الجزيئي للـ DNA، التضاعف، وبناء البروتين.",
      subject: "biology",
      grade: "grade3",
      teacherName: "أ. حسن محرم",
      category: "test",
      examType: "course-dependent",
      courseId: "course-004",
      courseTitle: "الأحياء والوراثة للثانوية العامة",
      triesAllowed: 1,
      durationMinutes: 60,
      passingPercentage: 65,
      showModelAnswers: false,
      randomizeQuestionsOrder: true,
      randomizeMCQChoices: true,
      examSections: [
        {
          id: "esec-004",
          title: "أسئلة الوراثة الجزيئية",
          questions: [
            {
              id: "q-005",
              questionName: "قواعد DNA",
              questionContent: "أي القواعد النيتروجينية ترتبط ببعضها بثلاثة روابط هيدروجينية؟",
              modelAnswer: "opt-3",
              type: "mcq",
              options: [
                { id: "opt-1", text: "الأدينين والثيمين" },
                { id: "opt-2", text: "الأدينين واليوراسيل" },
                { id: "opt-3", text: "الجوانين والسيتوسين" },
                { id: "opt-4", text: "الثيمين واليوراسيل" },
              ],
              grade: 8,
              required: true,
              questionType: "theoretical",
              difficulty: "medium",
              hasAnswerExplanation: true,
              answerExplanation: "الجوانين (G) والسيتوسين (C) يرتبطان بثلاثة روابط هيدروجينية.",
            },
          ],
        },
      ],
      numberOfQuestions: 20,
      numberOfStudents: 640,
      successRate: 69,
      timesUsed: 870,
      publishStatus: "published",
      createdAt: "2026-07-25T11:00:00Z",
    },
    {
      id: "exam-005",
      title: "اختبار قصير - مفاهيم المجال المغناطيسي",
      description: "اختبار سريع على وحدة التأثير المغناطيسي للتيار الكهربي.",
      subject: "physics",
      grade: "grade3",
      teacherName: "أ. محمد عبد المعبود",
      category: "quiz",
      examType: "independent",
      venue: "online",
      triesAllowed: 3,
      durationMinutes: 15,
      passingPercentage: 50,
      showModelAnswers: true,
      randomizeQuestionsOrder: true,
      randomizeMCQChoices: true,
      examSections: [
        {
          id: "esec-005",
          title: "أسئلة المجال المغناطيسي",
          questions: [
            {
              id: "q-006",
              questionName: "القاعدة اليدوية اليمنى",
              questionContent:
                "تُستخدم القاعدة اليدوية اليمنى لتحديد اتجاه المجال المغناطيسي حول سلك مستقيم. (صح/خطأ)",
              modelAnswer: "true",
              type: "true/false",
              grade: 5,
              required: true,
              questionType: "theoretical",
              difficulty: "easy",
              hasAnswerExplanation: false,
            },
          ],
        },
      ],
      numberOfQuestions: 5,
      numberOfStudents: 320,
      successRate: 82,
      timesUsed: 540,
      publishStatus: "published",
      createdAt: "2026-08-10T14:00:00Z",
    },
    {
      id: "exam-006",
      title: "امتحان تحديد المستوى - الرياضيات العامة",
      description: "اختبار تشخيصي لتحديد مستوى الطالب في الرياضيات قبل الالتحاق بالدورة.",
      subject: "mathematics",
      grade: "grade2",
      teacherName: "أ. أحمد سرور",
      category: "placement",
      examType: "independent",
      venue: "all",
      triesAllowed: 1,
      durationMinutes: 25,
      passingPercentage: 40,
      showModelAnswers: false,
      randomizeQuestionsOrder: false,
      randomizeMCQChoices: false,
      examSections: [
        {
          id: "esec-006",
          title: "المهارات الأساسية",
          questions: [
            {
              id: "q-007",
              questionName: "حل معادلة تربيعية",
              questionContent: "حل المعادلة: x² - 5x + 6 = 0",
              modelAnswer: "x = 2, x = 3",
              type: "text",
              grade: 10,
              required: true,
              questionType: "application-based",
              difficulty: "medium",
              hasAnswerExplanation: true,
              answerExplanation: "بالتحليل: (x-2)(x-3)=0 → x=2 أو x=3",
            },
          ],
        },
      ],
      numberOfQuestions: 12,
      numberOfStudents: 2100,
      successRate: 55,
      timesUsed: 2100,
      publishStatus: "published",
      createdAt: "2026-06-15T07:00:00Z",
    },
    {
      id: "exam-007",
      title: "امتحان الفصل الدراسي - اللغة العربية والنحو",
      description: "امتحان شامل للفصل الدراسي يتضمن الإعراب والبلاغة والتحليل الأدبي.",
      subject: "arabic",
      grade: "grade2",
      teacherName: "أ. وليد محسن",
      category: "comprehensive",
      examType: "course-dependent",
      courseId: "course-005",
      courseTitle: "اللغة العربية - النحو والبلاغة الشاملة",
      triesAllowed: 1,
      durationMinutes: 90,
      passingPercentage: 60,
      showModelAnswers: true,
      randomizeQuestionsOrder: false,
      randomizeMCQChoices: false,
      examSections: [
        {
          id: "esec-007",
          title: "النحو والإعراب",
          subtitle: "أسئلة تتعلق بالإعراب وتحليل الجمل",
          questions: [
            {
              id: "q-008",
              questionName: "إعراب الفاعل",
              questionContent: "أعرب الكلمة المبنية في: «جاءَ الطلابُ مبكرين».",
              modelAnswer: "الطلابُ: فاعل مرفوع وعلامة رفعه الضمة الظاهرة على آخره.",
              type: "text",
              grade: 15,
              required: true,
              questionType: "analytical",
              difficulty: "medium",
              hasAnswerExplanation: false,
            },
          ],
        },
      ],
      numberOfQuestions: 25,
      numberOfStudents: 890,
      successRate: 63,
      timesUsed: 1100,
      publishStatus: "draft",
      createdAt: "2026-08-12T10:00:00Z",
    },
    {
      id: "exam-008",
      title: "اختبار أعمال السنة - الكيمياء",
      description: "اختبار أعمال السنة الفصلية يشمل جميع التجارب العملية ونتائجها.",
      subject: "chemistry",
      grade: "grade3",
      teacherName: "د. إيهاب عبد العزيز",
      category: "yearWork",
      examType: "independent",
      venue: "center",
      triesAllowed: 1,
      durationMinutes: 50,
      passingPercentage: 70,
      showModelAnswers: false,
      randomizeQuestionsOrder: false,
      randomizeMCQChoices: false,
      examSections: [
        {
          id: "esec-008",
          title: "التجارب العملية",
          questions: [
            {
              id: "q-009",
              questionName: "تجربة الهلجنة",
              questionContent: "صف خطوات تجربة هلجنة الميثان مع الكلور تحت الأشعة فوق البنفسجية.",
              modelAnswer: "CH4 + Cl2 → CH3Cl + HCl (في ضوء UV)",
              type: "text",
              grade: 20,
              required: true,
              questionType: "practical",
              difficulty: "hard",
              hasAnswerExplanation: true,
              answerExplanation: "التفاعل تسلسلي يمر بمراحل البدء، النشر، والإنهاء.",
            },
          ],
        },
      ],
      numberOfQuestions: 6,
      numberOfStudents: 415,
      successRate: 48,
      timesUsed: 600,
      publishStatus: "scheduled",
      createdAt: "2026-08-08T09:00:00Z",
      scheduledAt: "2026-09-01T08:00:00Z",
    },
  ],

  en: [
    {
      id: "exam-001",
      title: "Comprehensive Exam on Electric Current & Ohm's Law",
      description:
        "### Final Comprehensive Exam\n\nCovers Unit 1 of the Physics curriculum including **Electric Current Intensity**, **Ohm's Law**, and closed circuit applications.\n\n- Duration: 45 minutes\n- Passing Score: 60%",
      subject: "physics",
      grade: "grade3",
      teacherName: "Mr. Mohamed Abdel Maaboud",
      category: "final",
      examType: "course-dependent",
      courseId: "course-001",
      courseTitle: "High School Physics - Full First Term Curriculum",
      triesAllowed: 1,
      durationMinutes: 45,
      passingPercentage: 60,
      showModelAnswers: true,
      randomizeQuestionsOrder: true,
      randomizeMCQChoices: false,
      examSections: [
        {
          id: "esec-001",
          title: "Part 1: Multiple Choice Questions",
          questions: [
            {
              id: "q-001",
              questionName: "Unit of Current",
              questionContent: "What is the SI unit for electric current intensity?",
              modelAnswer: "opt-1",
              type: "mcq",
              options: [
                { id: "opt-1", text: "Ampere (A)" },
                { id: "opt-2", text: "Volt (V)" },
                { id: "opt-3", text: "Ohm (Ω)" },
                { id: "opt-4", text: "Coulomb (C)" },
              ],
              grade: 5,
              required: true,
              questionType: "theoretical",
              difficulty: "easy",
              hasAnswerExplanation: true,
              answerExplanation:
                "The Ampere is the unit of electric current, equal to one Coulomb per second.",
            },
            {
              id: "q-002",
              questionName: "Ohm's Law Application",
              questionContent:
                "A circuit has resistance 10 Ω and potential difference 20 V. What is the current?",
              modelAnswer: "opt-2",
              type: "mcq",
              options: [
                { id: "opt-1", text: "0.5 A" },
                { id: "opt-2", text: "2 A" },
                { id: "opt-3", text: "200 A" },
                { id: "opt-4", text: "10 A" },
              ],
              grade: 10,
              required: true,
              questionType: "application-based",
              difficulty: "medium",
              hasAnswerExplanation: false,
            },
          ],
        },
      ],
      numberOfQuestions: 15,
      numberOfStudents: 832,
      successRate: 74,
      timesUsed: 1250,
      publishStatus: "published",
      createdAt: "2026-08-01T10:00:00Z",
    },
    {
      id: "exam-002",
      title: "Midterm Exam – Organic Chemistry",
      description:
        "### Midterm Examination\n\nCovers the aliphatic hydrocarbons unit (Alkanes, Alkenes, Alkynes) and organic compound nomenclature.",
      subject: "chemistry",
      grade: "grade3",
      teacherName: "Dr. Ihab Abdelaziz",
      category: "midterm",
      examType: "course-dependent",
      courseId: "course-002",
      courseTitle: "Organic Chemistry Mastery",
      triesAllowed: 2,
      durationMinutes: 30,
      passingPercentage: 50,
      showModelAnswers: false,
      randomizeQuestionsOrder: true,
      randomizeMCQChoices: true,
      examSections: [
        {
          id: "esec-002",
          title: "Compound Nomenclature",
          questions: [
            {
              id: "q-003",
              questionName: "Alkane Naming",
              questionContent: "What is the correct IUPAC name for CH3-CH2-CH3?",
              modelAnswer: "opt-1",
              type: "mcq",
              options: [
                { id: "opt-1", text: "Propane" },
                { id: "opt-2", text: "Ethane" },
                { id: "opt-3", text: "Butane" },
                { id: "opt-4", text: "Methane" },
              ],
              grade: 5,
              required: true,
              questionType: "theoretical",
              difficulty: "easy",
              hasAnswerExplanation: false,
            },
          ],
        },
      ],
      numberOfQuestions: 10,
      numberOfStudents: 510,
      successRate: 61,
      timesUsed: 680,
      publishStatus: "published",
      createdAt: "2026-08-05T09:00:00Z",
    },
    {
      id: "exam-003",
      title: "Unit Exam – Triangle & Polygon Similarity",
      description:
        "### Unit 1 Exam\n\nTests the concept of polygon and triangle similarity and applications of Thales' theorem.",
      subject: "mathematics",
      grade: "grade1",
      teacherName: "Mr. Ahmed Sroor",
      category: "unit",
      examType: "course-dependent",
      courseId: "course-003",
      courseTitle: "Mathematics Fundamentals & Geometry",
      triesAllowed: 1,
      durationMinutes: 40,
      passingPercentage: 55,
      showModelAnswers: true,
      randomizeQuestionsOrder: false,
      randomizeMCQChoices: false,
      examSections: [
        {
          id: "esec-003",
          title: "Similarity Questions",
          questions: [
            {
              id: "q-004",
              questionName: "Similarity Ratio",
              questionContent:
                "If triangles ABC and DEF are similar with a ratio of 1:3, what is the ratio of their areas?",
              modelAnswer: "1:9",
              type: "text",
              grade: 10,
              required: true,
              questionType: "analytical",
              difficulty: "hard",
              hasAnswerExplanation: true,
              answerExplanation: "Area ratio = square of similarity ratio = (1/3)² = 1/9",
            },
          ],
        },
      ],
      numberOfQuestions: 8,
      numberOfStudents: 1240,
      successRate: 58,
      timesUsed: 1950,
      publishStatus: "published",
      createdAt: "2026-07-20T08:00:00Z",
    },
    {
      id: "exam-004",
      title: "Biology Exam – Genetics & DNA",
      description:
        "### Unit 2: Molecular Genetics\n\nCovers the molecular structure of DNA, replication, and protein synthesis.",
      subject: "biology",
      grade: "grade3",
      teacherName: "Mr. Hassan Mohram",
      category: "test",
      examType: "course-dependent",
      courseId: "course-004",
      courseTitle: "High School Biology & Genetics",
      triesAllowed: 1,
      durationMinutes: 60,
      passingPercentage: 65,
      showModelAnswers: false,
      randomizeQuestionsOrder: true,
      randomizeMCQChoices: true,
      examSections: [
        {
          id: "esec-004",
          title: "Molecular Genetics Questions",
          questions: [
            {
              id: "q-005",
              questionName: "DNA Base Pairing",
              questionContent: "Which nitrogen bases are connected by three hydrogen bonds?",
              modelAnswer: "opt-3",
              type: "mcq",
              options: [
                { id: "opt-1", text: "Adenine & Thymine" },
                { id: "opt-2", text: "Adenine & Uracil" },
                { id: "opt-3", text: "Guanine & Cytosine" },
                { id: "opt-4", text: "Thymine & Uracil" },
              ],
              grade: 8,
              required: true,
              questionType: "theoretical",
              difficulty: "medium",
              hasAnswerExplanation: true,
              answerExplanation: "Guanine (G) and Cytosine (C) form three hydrogen bonds.",
            },
          ],
        },
      ],
      numberOfQuestions: 20,
      numberOfStudents: 640,
      successRate: 69,
      timesUsed: 870,
      publishStatus: "published",
      createdAt: "2026-07-25T11:00:00Z",
    },
    {
      id: "exam-005",
      title: "Quick Quiz – Magnetic Field Concepts",
      description: "A rapid quiz on the unit covering the magnetic effect of electric current.",
      subject: "physics",
      grade: "grade3",
      teacherName: "Mr. Mohamed Abdel Maaboud",
      category: "quiz",
      examType: "independent",
      venue: "online",
      triesAllowed: 3,
      durationMinutes: 15,
      passingPercentage: 50,
      showModelAnswers: true,
      randomizeQuestionsOrder: true,
      randomizeMCQChoices: true,
      examSections: [
        {
          id: "esec-005",
          title: "Magnetic Field Questions",
          questions: [
            {
              id: "q-006",
              questionName: "Right-Hand Rule",
              questionContent:
                "The right-hand rule is used to determine the direction of the magnetic field around a straight conductor. (True/False)",
              modelAnswer: "true",
              type: "true/false",
              grade: 5,
              required: true,
              questionType: "theoretical",
              difficulty: "easy",
              hasAnswerExplanation: false,
            },
          ],
        },
      ],
      numberOfQuestions: 5,
      numberOfStudents: 320,
      successRate: 82,
      timesUsed: 540,
      publishStatus: "published",
      createdAt: "2026-08-10T14:00:00Z",
    },
    {
      id: "exam-006",
      title: "Placement Test – General Mathematics",
      description:
        "A diagnostic test to assess student level in mathematics before enrolling in a course.",
      subject: "mathematics",
      grade: "grade2",
      teacherName: "Mr. Ahmed Sroor",
      category: "placement",
      examType: "independent",
      venue: "all",
      triesAllowed: 1,
      durationMinutes: 25,
      passingPercentage: 40,
      showModelAnswers: false,
      randomizeQuestionsOrder: false,
      randomizeMCQChoices: false,
      examSections: [
        {
          id: "esec-006",
          title: "Core Skills",
          questions: [
            {
              id: "q-007",
              questionName: "Solving a Quadratic Equation",
              questionContent: "Solve the equation: x² - 5x + 6 = 0",
              modelAnswer: "x = 2, x = 3",
              type: "text",
              grade: 10,
              required: true,
              questionType: "application-based",
              difficulty: "medium",
              hasAnswerExplanation: true,
              answerExplanation: "Factoring: (x-2)(x-3)=0 → x=2 or x=3",
            },
          ],
        },
      ],
      numberOfQuestions: 12,
      numberOfStudents: 2100,
      successRate: 55,
      timesUsed: 2100,
      publishStatus: "published",
      createdAt: "2026-06-15T07:00:00Z",
    },
    {
      id: "exam-007",
      title: "Semester Exam – Arabic Language & Grammar",
      description:
        "Comprehensive semester exam including parsing (إعراب), rhetoric, and literary analysis.",
      subject: "arabic",
      grade: "grade2",
      teacherName: "Mr. Waleed Mohsen",
      category: "comprehensive",
      examType: "course-dependent",
      courseId: "course-005",
      courseTitle: "Arabic Language - Comprehensive Grammar & Rhetoric",
      triesAllowed: 1,
      durationMinutes: 90,
      passingPercentage: 60,
      showModelAnswers: true,
      randomizeQuestionsOrder: false,
      randomizeMCQChoices: false,
      examSections: [
        {
          id: "esec-007",
          title: "Grammar & Parsing",
          subtitle: "Questions related to sentence parsing and analysis",
          questions: [
            {
              id: "q-008",
              questionName: "Subject Parsing",
              questionContent: "Parse the underlined word in: 'The students came early.'",
              modelAnswer: "Subject — nominative case.",
              type: "text",
              grade: 15,
              required: true,
              questionType: "analytical",
              difficulty: "medium",
              hasAnswerExplanation: false,
            },
          ],
        },
      ],
      numberOfQuestions: 25,
      numberOfStudents: 890,
      successRate: 63,
      timesUsed: 1100,
      publishStatus: "draft",
      createdAt: "2026-08-12T10:00:00Z",
    },
    {
      id: "exam-008",
      title: "Year Work Assessment – Chemistry",
      description: "Year work assessment covering all practical experiments and their results.",
      subject: "chemistry",
      grade: "grade3",
      teacherName: "Dr. Ihab Abdelaziz",
      category: "yearWork",
      examType: "independent",
      venue: "center",
      triesAllowed: 1,
      durationMinutes: 50,
      passingPercentage: 70,
      showModelAnswers: false,
      randomizeQuestionsOrder: false,
      randomizeMCQChoices: false,
      examSections: [
        {
          id: "esec-008",
          title: "Practical Experiments",
          questions: [
            {
              id: "q-009",
              questionName: "Halogenation Experiment",
              questionContent:
                "Describe the steps of the methane halogenation experiment with chlorine under UV light.",
              modelAnswer: "CH4 + Cl2 → CH3Cl + HCl (under UV light)",
              type: "text",
              grade: 20,
              required: true,
              questionType: "practical",
              difficulty: "hard",
              hasAnswerExplanation: true,
              answerExplanation:
                "The reaction is a chain reaction going through initiation, propagation, and termination steps.",
            },
          ],
        },
      ],
      numberOfQuestions: 6,
      numberOfStudents: 415,
      successRate: 48,
      timesUsed: 600,
      publishStatus: "scheduled",
      createdAt: "2026-08-08T09:00:00Z",
      scheduledAt: "2026-09-01T08:00:00Z",
    },
  ],
};
