import { Course } from "@/types/course";

export const mockCoursesData: Record<"ar" | "en", Course[]> = {
  ar: [
    {
      id: "course-001",
      coverImage: "/courses/physics.jpg",
      title: "الفيزياء للثانوية العامة - منهج الترم الأول كامل",
      description:
        "شرح شامل ومفصل لمنهج الفيزياء للصف الثالث الثانوي مع تطبيقات عملي ومسائل محلولة وإتاحة اختبارات دورية بعد كل فصل.",
      previewVideoLink: "https://www.youtube.com/watch?v=u31qwQUeGuM",
      subject: "الفيزياء",
      grade: "الصف الثالث الثانوي",
      teacherName: "أ. محمد عبد المعبود",
      period: "termBased",
      date: "2026-09-01",
      numberOfLessons: 18,
      price: 450,
      isFree: false,
      currency: "EGP",
      hasOffer: true,
      offerPercentage: "15% خصم",
      hasTimeLimit: true,
      timeLimitValue: 30,
      isSplitToGroups: true,
      venue: "all",
      numberOfParticipants: 1250,
      isDraft: false,
      sections: [
        {
          id: "sec-001",
          title: "الفصل الأول: التيار الكهربي وقانون أوم وقانونا كيرشوف",
          isDraft: false,
          isLinkedToExam: true,
          linkedExam: {
            sectionId: "sec-001",
            examContent: {
              id: "exam-sec-001",
              title: "امتحان شامل على التيار الكهربي وقانون أوم",
              passingScore: 70,
              totalGrade: 100,
              questions: [
                {
                  id: "q-001",
                  questionText: "ما هي وحدة قياس شدة التيار الكهربي في النظام الدولي؟",
                  options: [
                    { id: "opt-1", text: "أمبير (Ampere)" },
                    { id: "opt-2", text: "فولت (Volt)" },
                    { id: "opt-3", text: "أوم (Ohm)" },
                    { id: "opt-4", text: "كولوم (Coulomb)" },
                  ],
                  correctAnswer: "opt-1",
                  grade: 10,
                  explanation: "الأمبير هو وحدة قياس شدة التيار الكهربي المقاسة بكولوم لكل ثانية.",
                },
              ],
            },
          },
          isRequiredPassExamForNextSection: true,
          lessons: [
            {
              id: "les-001",
              title: "الدرس الأول: شدة التيار الكهربي وفرق الجهد",
              lectureVideoLink: "https://www.youtube.com/watch?v=u31qwQUeGuM",
              writtenText:
                "مفهوم الشحنة الكهربية وحركتها داخل الموصلات، وحساب شدة التيار وفرق الجهد الكهربي.",
              attachments: [
                {
                  id: "att-001",
                  title: "ملخص قوانين التيار الكهربي.pdf",
                  fileUrl: "/assets/docs/physics_summary.pdf",
                  fileType: "pdf",
                  sizeInBytes: 2450000,
                },
              ],
            },
          ],
          tests: [],
        },
      ],
    },
    {
      id: "course-002",
      coverImage: "/courses/chemistry.jpg",
      title: "الكيمياء العضوية والتفوق فيها",
      description:
        "دورة مكثفة في الكيمياء العضوية تتضمن المجموعات الوظيفية والتسمية النظامية والتفاعلات الكيميائية.",
      previewVideoLink: "https://www.youtube.com/watch?v=u31qwQUeGuM",
      subject: "الكيمياء",
      grade: "الصف الثالث الثانوي",
      teacherName: "د. إيهاب عبد العزيز",
      period: "monthly",
      date: "2026-09-15",
      numberOfLessons: 12,
      price: 200,
      isFree: false,
      currency: "EGP",
      hasOffer: false,
      hasTimeLimit: false,
      isSplitToGroups: false,
      venue: "online",
      numberOfParticipants: 850,
      isDraft: false,
      sections: [],
    },
    {
      id: "course-003",
      coverImage: "/courses/math.jpg",
      title: "أساسيات الرياضيات والفرع الهندسي",
      description:
        "دورة تجريبية مجانية لجميع طلاب الصف الأول الثانوي لتعلم أساسيات الهندسة والجبر.",
      previewVideoLink: "",
      subject: "الرياضيات",
      grade: "الصف الأول الثانوي",
      teacherName: "أ. أحمد سرور",
      period: "yearly",
      date: "2026-10-01",
      numberOfLessons: 6,
      price: 0,
      isFree: true,
      currency: "EGP",
      hasOffer: false,
      hasTimeLimit: true,
      timeLimitValue: 14,
      isSplitToGroups: false,
      venue: "center",
      numberOfParticipants: 3200,
      isDraft: true,
      sections: [],
    },
    {
      id: "course-004",
      coverImage: "/courses/biology.webp",
      title: "الأحياء والوراثة للثانوية العامة",
      description: "شرح كامل لمادة الأحياء والوراثة والتركيب الخلوي وتطبيقات على الحمض النووي DNA.",
      subject: "الأحياء",
      grade: "الصف الثالث الثانوي",
      teacherName: "أ. حسن محرم",
      period: "termBased",
      date: "2026-08-20",
      numberOfLessons: 14,
      price: 380,
      isFree: false,
      currency: "EGP",
      hasOffer: true,
      offerPercentage: "10% خصم",
      hasTimeLimit: false,
      isSplitToGroups: true,
      venue: "online",
      numberOfParticipants: 920,
      isDraft: false,
      sections: [],
    },
    {
      id: "course-005",
      coverImage: "/courses/arabic.jpg",
      title: "اللغة العربية - النحو والبلاغة الشاملة",
      description:
        "مساق النحو والبلاغة وإعراب الجمل للثانوية العامة مع قواعد ومسائل اختبارات سابقة.",
      subject: "اللغة العربية",
      grade: "الصف الثاني الثانوي",
      teacherName: "أ. وليد محسن",
      period: "monthly",
      date: "2026-09-10",
      numberOfLessons: 20,
      price: 250,
      isFree: false,
      currency: "EGP",
      hasOffer: false,
      hasTimeLimit: false,
      isSplitToGroups: false,
      venue: "all",
      numberOfParticipants: 1450,
      isDraft: false,
      sections: [],
    },
    {
      id: "course-006",
      coverImage: "/courses/geography.webp",
      title: "الجغرافيا السياسية والاستراتيجيات",
      description:
        "شرح خرائط الجغرافيا السياسية والدول المقررة للصف الثالث الثانوي بأحدث الأساليب.",
      subject: "الجغرافيا",
      grade: "الصف الثالث الثانوي",
      teacherName: "أ. أيمن الماضي",
      period: "monthly",
      date: "2026-09-25",
      numberOfLessons: 10,
      price: 180,
      isFree: false,
      currency: "EGP",
      hasOffer: false,
      hasTimeLimit: true,
      timeLimitValue: 20,
      isSplitToGroups: true,
      venue: "center",
      numberOfParticipants: 640,
      isDraft: true,
      sections: [],
    },
    {
      id: "course-007",
      coverImage: "/courses/english.png",
      title: "اللغة الإنجليزية - إتقان القواعد والقراءة",
      description: "تطوير مهارات القراءة والكتابة وحل قطع الفهم والقواعد المعقدة للثانوية العامة.",
      subject: "اللغة الإنجليزية",
      grade: "الصف الثالث الثانوي",
      teacherName: "مستر شريف المصري",
      period: "termBased",
      date: "2026-08-15",
      numberOfLessons: 16,
      price: 320,
      isFree: false,
      currency: "EGP",
      hasOffer: true,
      offerPercentage: "20% خصم",
      hasTimeLimit: false,
      isSplitToGroups: false,
      venue: "online",
      numberOfParticipants: 2100,
      isDraft: false,
      sections: [],
    },
    {
      id: "course-008",
      coverImage: "/courses/programming.png",
      title: "مقدمة في البرمجة والتفكير المنطقي",
      description: "دورة للمرحلة الثانوية لتعلم التفكير البرمجي ولغة خوارزمية البداية.",
      subject: "الحاسب الآلي",
      grade: "الصف الأول الثانوي",
      teacherName: "مهندس عمرو خالد",
      period: "yearly",
      date: "2026-10-05",
      numberOfLessons: 8,
      price: 0,
      isFree: true,
      currency: "EGP",
      hasOffer: false,
      hasTimeLimit: false,
      isSplitToGroups: false,
      venue: "online",
      numberOfParticipants: 4100,
      isDraft: false,
      sections: [],
    },
    {
      id: "course-009",
      coverImage: "/courses/history.jpg",
      title: "التاريخ الحديث والمعاصر - الفصل الأول والثاني",
      description: "مساق تاريخ مصر الحديث والحروب والأحداث التاريخية الهامة للثانوية العامة.",
      subject: "التاريخ",
      grade: "الصف الثالث الثانوي",
      teacherName: "أ. سامح كاملاً",
      period: "monthly",
      date: "2026-09-18",
      numberOfLessons: 15,
      price: 220,
      isFree: false,
      currency: "EGP",
      hasOffer: false,
      hasTimeLimit: true,
      timeLimitValue: 15,
      isSplitToGroups: true,
      venue: "center",
      numberOfParticipants: 530,
      isDraft: true,
      sections: [],
    },
    {
      id: "course-010",
      coverImage: "/courses/philosophy.jpg",
      title: "الفلسفة والمنطق - الجزء الأول",
      description: "طرق التفكير الفلسفي والمنطق الصوري والرياضيات المنطقية.",
      subject: "الفلسفة",
      grade: "الصف الثاني الثانوي",
      teacherName: "د. تامر الملا",
      period: "termBased",
      date: "2026-09-02",
      numberOfLessons: 11,
      price: 190,
      isFree: false,
      currency: "EGP",
      hasOffer: false,
      hasTimeLimit: false,
      isSplitToGroups: false,
      venue: "all",
      numberOfParticipants: 780,
      isDraft: false,
      sections: [],
    },
  ],
  en: [
    {
      id: "course-001",
      coverImage: "/courses/physics.jpg",
      title: "High School Physics - Complete First Term Curriculum",
      description:
        "Comprehensive and detailed explanation of the 3rd Secondary Physics curriculum with practical applications and solved problems.",
      previewVideoLink: "https://www.youtube.com/watch?v=u31qwQUeGuM",
      subject: "Physics",
      grade: "Grade 12 (3rd Secondary)",
      teacherName: "Mr. Mohamed Abdel-Maboud",
      period: "termBased",
      date: "2026-09-01",
      numberOfLessons: 18,
      price: 450,
      isFree: false,
      currency: "EGP",
      hasOffer: true,
      offerPercentage: "15% off",
      hasTimeLimit: true,
      timeLimitValue: 30,
      isSplitToGroups: true,
      venue: "all",
      numberOfParticipants: 1250,
      isDraft: false,
      sections: [
        {
          id: "sec-001",
          title: "Chapter 1: Electric Current, Ohm's Law & Kirchhoff's Laws",
          isDraft: false,
          isLinkedToExam: true,
          linkedExam: {
            sectionId: "sec-001",
            examContent: {
              id: "exam-sec-001",
              title: "Comprehensive Exam on Electric Current & Ohm's Law",
              passingScore: 70,
              totalGrade: 100,
              questions: [
                {
                  id: "q-001",
                  questionText: "What is the SI unit of Electric Current Intensity?",
                  options: [
                    { id: "opt-1", text: "Ampere (A)" },
                    { id: "opt-2", text: "Volt (V)" },
                    { id: "opt-3", text: "Ohm (Ω)" },
                    { id: "opt-4", text: "Coulomb (C)" },
                  ],
                  correctAnswer: "opt-1",
                  grade: 10,
                  explanation: "Ampere measures current intensity as Coulombs per second.",
                },
              ],
            },
          },
          isRequiredPassExamForNextSection: true,
          lessons: [
            {
              id: "les-001",
              title: "Lesson 1: Electric Current Intensity & Potential Difference",
              lectureVideoLink: "https://www.youtube.com/watch?v=u31qwQUeGuM",
              writtenText:
                "Concept of electric charge movement in conductors, measuring current intensity and voltage.",
              attachments: [
                {
                  id: "att-001",
                  title: "Physics Formulas Summary.pdf",
                  fileUrl: "/assets/docs/physics_summary.pdf",
                  fileType: "pdf",
                  sizeInBytes: 2450000,
                },
              ],
            },
          ],
          tests: [],
        },
      ],
    },
    {
      id: "course-002",
      coverImage: "/courses/chemistry.jpg",
      title: "Organic Chemistry Mastery",
      description:
        "An intensive course in Organic Chemistry covering functional groups, IUPAC nomenclature, and chemical reactions.",
      previewVideoLink: "https://www.youtube.com/watch?v=u31qwQUeGuM",
      subject: "Chemistry",
      grade: "Grade 12 (3rd Secondary)",
      teacherName: "Dr. Ehab Abdel-Aziz",
      period: "monthly",
      date: "2026-09-15",
      numberOfLessons: 12,
      price: 200,
      isFree: false,
      currency: "EGP",
      hasOffer: false,
      hasTimeLimit: false,
      isSplitToGroups: false,
      venue: "online",
      numberOfParticipants: 850,
      isDraft: false,
      sections: [],
    },
    {
      id: "course-003",
      coverImage: "/courses/math.jpg",
      title: "Mathematics Fundamentals & Geometry",
      description:
        "Free introductory course for 1st Secondary students covering core algebra and geometry concepts.",
      previewVideoLink: "",
      subject: "Mathematics",
      grade: "Grade 10 (1st Secondary)",
      teacherName: "Mr. Ahmed Sroor",
      period: "yearly",
      date: "2026-10-01",
      numberOfLessons: 6,
      price: 0,
      isFree: true,
      currency: "EGP",
      hasOffer: false,
      hasTimeLimit: true,
      timeLimitValue: 14,
      isSplitToGroups: false,
      venue: "center",
      numberOfParticipants: 3200,
      isDraft: true,
      sections: [],
    },
    {
      id: "course-004",
      coverImage: "/courses/biology.webp",
      title: "High School Biology & Genetics",
      description:
        "Complete explanation of Biology, cellular structures, and DNA application topics.",
      subject: "Biology",
      grade: "Grade 12 (3rd Secondary)",
      teacherName: "Mr. Hassan Moharram",
      period: "termBased",
      date: "2026-08-20",
      numberOfLessons: 14,
      price: 380,
      isFree: false,
      currency: "EGP",
      hasOffer: true,
      offerPercentage: "10% off",
      hasTimeLimit: false,
      isSplitToGroups: true,
      venue: "online",
      numberOfParticipants: 920,
      isDraft: false,
      sections: [],
    },
    {
      id: "course-005",
      coverImage: "/courses/arabic.jpg",
      title: "Arabic Language - Grammar & Rhetoric",
      description: "Comprehensive grammar and rhetoric course for high school students.",
      subject: "Arabic",
      grade: "Grade 11 (2nd Secondary)",
      teacherName: "Mr. Waleed Mohsen",
      period: "monthly",
      date: "2026-09-10",
      numberOfLessons: 20,
      price: 250,
      isFree: false,
      currency: "EGP",
      hasOffer: false,
      hasTimeLimit: false,
      isSplitToGroups: false,
      venue: "all",
      numberOfParticipants: 1450,
      isDraft: false,
      sections: [],
    },
    {
      id: "course-006",
      coverImage: "/courses/geography.webp",
      title: "Political Geography & Strategies",
      description: "Maps and political geography curriculum for 3rd Secondary grade.",
      subject: "Geography",
      grade: "Grade 12 (3rd Secondary)",
      teacherName: "Mr. Ayman El-Mady",
      period: "monthly",
      date: "2026-09-25",
      numberOfLessons: 10,
      price: 180,
      isFree: false,
      currency: "EGP",
      hasOffer: false,
      hasTimeLimit: true,
      timeLimitValue: 20,
      isSplitToGroups: true,
      venue: "center",
      numberOfParticipants: 640,
      isDraft: true,
      sections: [],
    },
    {
      id: "course-007",
      coverImage: "/courses/english.png",
      title: "English Language - Mastery & Grammar",
      description: "Developing reading, writing, comprehension and advanced grammar skills.",
      subject: "English",
      grade: "Grade 12 (3rd Secondary)",
      teacherName: "Mr. Sherif El-Masry",
      period: "termBased",
      date: "2026-08-15",
      numberOfLessons: 16,
      price: 320,
      isFree: false,
      currency: "EGP",
      hasOffer: true,
      offerPercentage: "20% off",
      hasTimeLimit: false,
      isSplitToGroups: false,
      venue: "online",
      numberOfParticipants: 2100,
      isDraft: false,
      sections: [],
    },
    {
      id: "course-008",
      coverImage: "/courses/programming.png",
      title: "Introduction to Computer Science & Logic",
      description: "High school introductory course to learn computational thinking.",
      subject: "Computer Science",
      grade: "Grade 10 (1st Secondary)",
      teacherName: "Eng. Amr Khaled",
      period: "yearly",
      date: "2026-10-05",
      numberOfLessons: 8,
      price: 0,
      isFree: true,
      currency: "EGP",
      hasOffer: false,
      hasTimeLimit: false,
      isSplitToGroups: false,
      venue: "online",
      numberOfParticipants: 4100,
      isDraft: false,
      sections: [],
    },
    {
      id: "course-009",
      coverImage: "/courses/history.jpg",
      title: "Modern & Contemporary History - Part 1",
      description: "Modern history of Egypt and significant historical events.",
      subject: "History",
      grade: "Grade 12 (3rd Secondary)",
      teacherName: "Mr. Sameh Kamel",
      period: "monthly",
      date: "2026-09-18",
      numberOfLessons: 15,
      price: 220,
      isFree: false,
      currency: "EGP",
      hasOffer: false,
      hasTimeLimit: true,
      timeLimitValue: 15,
      isSplitToGroups: true,
      venue: "center",
      numberOfParticipants: 530,
      isDraft: true,
      sections: [],
    },
    {
      id: "course-010",
      coverImage: "/courses/philosophy.jpg",
      title: "Philosophy & Logic - Part 1",
      description: "Philosophical thinking methods, formal logic, and symbolic logic.",
      subject: "Philosophy",
      grade: "Grade 11 (2nd Secondary)",
      teacherName: "Dr. Tamer El-Molla",
      period: "termBased",
      date: "2026-09-02",
      numberOfLessons: 11,
      price: 190,
      isFree: false,
      currency: "EGP",
      hasOffer: false,
      hasTimeLimit: false,
      isSplitToGroups: false,
      venue: "all",
      numberOfParticipants: 780,
      isDraft: false,
      sections: [],
    },
  ],
};
