import { mockLessonsData } from "./mockLessonsData";
import { Course, Lesson } from "@/types/course";

const getSectionLessons = (locale: "ar" | "en", courseId: string, sectionId: string): Lesson[] => {
  return mockLessonsData[locale].filter(
    (lesson) => lesson.courseId === courseId && lesson.sectionId === sectionId,
  );
};

export const mockCoursesData: Record<"ar" | "en", Course[]> = {
  ar: [
    {
      id: "course-001",
      coverImage: "/courses/physics.jpg",
      title: "الفيزياء للثانوية العامة - منهج الترم الأول كامل",
      description:
        "### نبذة عن دورة الفيزياء للثانوية العامة\n\nتعتبر هذه الدورة *الدليل المتكامل* لطلاب **الصف الثالث الثانوي** في مادة الفيزياء للترم الأول. تم إعداد المحتوى ليغطي جميع أجزاء المنهج بأسلوب مبسط وعميق يعتمد على الفهم والتفكير لا الحفظ والتلقين.\n\n#### أهداف الدورة المنهجية:\n1. **استيعاب المفاهيم الأساسية**: فهم الدوائر الكهربية، الشحنات، وفرق الجهد.\n2. **حل المسائل المتقدمة**: التدريب على امتحانات الأعوام السابقة والتفكير الابتكاري.\n3. **التطبيق العملي**: ربط القوانين النظرية بالتطبيقات الحياتية والتجارب المعملية.\n\n#### محاور المنهج بالتفصيل:\n- **التيار الكهربي وقانون أوم**: دراسة شدة التيار، المقاومة النوعية $R = \\rho \\frac{L}{A}$، والتوصيل على التوالي والتوازي.\n- **قوانين كيرشوف**: طرق حل الدوائر الكهربية المعقدة باستخدام قانون حفظ الشحنة وقانون حفظ الطاقة.\n- **المجال المغناطيسي والقوة المغناطيسية**: تحديد اتجاهات المجال وحساب عزم الازدواج وعزم ثنائي القطب.\n\n> **نصيحة للمذاكرة:** يُنصح بحل الأسئلة التفاعلية بعد كل درس مباشرة لترسيخ المعلومات وتحديد نقاط القوة والضعف.",
      previewVideoLink: "https://www.youtube.com/watch?v=u31qwQUeGuM",
      subject: "الفيزياء",
      grade: "الصف الثالث الثانوي",
      teacherName: "أ. محمد عبد المعبود",
      period: "termBased",
      date: "2026-09-01",
      numberOfLessons: 18,
      price: 450,
      isFree: false,
      currency: "EGP",
      hasOffer: true,
      offerPercentage: "15% خصم",
      hasTimeLimit: true,
      timeLimitValue: 30,
      isSplitToGroups: true,
      venue: "all",
      numberOfParticipants: 1250,
      isDraft: false,
      sections: [
        {
          id: "sec-001",
          title: "الفصل الأول: التيار الكهربي وقانون أوم وقانونا كيرشوف",
          isDraft: false,
          isLinkedToExam: true,
          linkedExamId: "exam-001", // FK → Exam.id
          isRequiredPassExamForNextSection: true,
          lessons: getSectionLessons("ar", "course-001", "sec-001"),
        },
        {
          id: "sec-002",
          title: "الفصل الثاني: التأثير المغناطيسي للتيار الكهربي وأجهزة القياس",
          isDraft: false,
          isLinkedToExam: false,
          isRequiredPassExamForNextSection: false,
          lessons: getSectionLessons("ar", "course-001", "sec-002"),
        },
      ],
    },
    {
      id: "course-002",
      coverImage: "/courses/chemistry.jpg",
      title: "الكيمياء العضوية والتفوق فيها",
      description:
        "### تفاصيل المنهج والدورة\n\nتعتبر **الكيمياء العضوية** من أهم وأمتع فروع الكيمياء لطلاب الثانوية العامة، حيث تشكل جزءاً كبيراً من الدرجة النهائية. تقدم هذه الدورة شرحاً منهجياً دقيقاً لكل تفاعل ومعادلة.\n\n#### المخرجات التعليمية المتوقعة:\n- إتقان تسمية المركبات العضوية حسب **نظام التسمية الدولي (IUPAC)**.\n- فهم ميكانيكية التفاعلات مثل *الإضافة، الاستبدال، والأكسدة والاختزال*.\n- التمييز بين المجموعات الوظيفية المختلفة وتأثيرها على الخواص الفيزيائية والكيميائية.\n\n```text\nتفاعل هلجنة الألكانات (مثال):\nCH4 + Cl2 --(اشعة فوق بنفسجية UV)--> CH3Cl + HCl\n```\n\n> **ملاحظة:** يتم تقديم ملخصات تشجيعية ورسومات مبسطة لسلاسل التفاعلات الكيميائية لتسهيل الحفظ والمراجعة.",
      previewVideoLink: "https://www.youtube.com/watch?v=u31qwQUeGuM",
      subject: "الكيمياء",
      grade: "الصف الثالث الثانوي",
      teacherName: "د. إيهاب عبد العزيز",
      period: "monthly",
      date: "2026-09-15",
      numberOfLessons: 12,
      price: 200,
      isFree: false,
      currency: "EGP",
      hasOffer: false,
      hasTimeLimit: false,
      isSplitToGroups: false,
      venue: "online",
      numberOfParticipants: 850,
      isDraft: false,
      sections: [
        {
          id: "sec-003",
          title: "الفصل الأول: الهيدروكربونات الأليفاتية والتسمية",
          isDraft: false,
          isLinkedToExam: true,
          linkedExamId: "exam-002", // FK → Exam.id
          isRequiredPassExamForNextSection: false,
          lessons: getSectionLessons("ar", "course-002", "sec-003"),
        },
      ],
    },
    {
      id: "course-003",
      coverImage: "/courses/math.jpg",
      title: "أساسيات الرياضيات والفرع الهندسي",
      description:
        "### دورة تاسيسية مجانية لجميع طلاب الصف الأول الثانوي\n\nنهدف من خلال هذه الدورة إلى بناء *قاعدة رياضية متينة* تمكن الطالب من التفوق في مراحل الثانوية العامة المختلفة. تركز الدورة على الفهم المنطقي وتحليل المشكلات الرياضياتية.\n\n#### محتويات الكورس:\n- **وحدة الجبر**: العلاقات والدوال، تحديد نوع جذري المعادلة التربيعية، والمتتابعات.\n- **وحدة الهندسة المستوية**: تشابه المضلعات والمثلثات، نظرية تاليس، والمماس والوتر.\n- **حساب المثلثات**: الزوايا الموجهة، القياس الدائري والستيني، والدوال المثلثية الأساسية.\n\n```text\nقانون المميز للمعادلة التربيعية:\nΔ = b^2 - 4ac\n```\n\n> **تنبيه:** هذه الدورة مجانية بالكامل ومتاحة لجميع الطلاب الراغبين في تقوية مهاراتهم في الرياضيات.",
      previewVideoLink: "",
      subject: "الرياضيات",
      grade: "الصف الأول الثانوي",
      teacherName: "أ. أحمد سرور",
      period: "yearly",
      date: "2026-10-01",
      numberOfLessons: 6,
      price: 0,
      isFree: true,
      currency: "EGP",
      hasOffer: false,
      hasTimeLimit: true,
      timeLimitValue: 14,
      isSplitToGroups: false,
      venue: "center",
      numberOfParticipants: 3200,
      isDraft: true,
      sections: [
        {
          id: "sec-004",
          title: "الفصل الأول: تشابه المثلثات والمضلعات",
          isDraft: false,
          isLinkedToExam: true,
          linkedExamId: "exam-003", // FK → Exam.id
          isRequiredPassExamForNextSection: false,
          lessons: getSectionLessons("ar", "course-003", "sec-004"),
        },
      ],
    },
    {
      id: "course-004",
      coverImage: "/courses/biology.webp",
      title: "الأحياء والوراثة للثانوية العامة",
      description:
        "### دليل الأحياء والتركيب الجيني\n\nتعتبر مادة الأحياء من المواد الشيقة التي تعتمد على الاستيعاب البصري والربط بين الوظائف الحيوية والتركيب الخلوي. تقدم هذه الدورة رحلة استكشافية في عالم الخلية والوراثة.\n\n#### النقاط الأساسية المطروحة:\n- **التركيب الخلوي والجزيئي**: دراسة النواة، الكروموسومات، والحمض النووي DNA.\n- **تضاعف DNA وبناء البروتين**: ميكانيكية التضاعف ودور RNA وأنواع الأنزيمات.\n- **الهندسة الوراثية**: تطبيقات البيوتكنولوجي، الجينوم البشري، والإنزيمات القاطعة.\n\n> **معلومة هامة:** يحتوي كل درس على مجسمات ثلاثية الأبعاد ورسومات توضيحية لتسهيل استيعاب التفاصيل الدقيقة.",
      previewVideoLink: "https://www.youtube.com/watch?v=u31qwQUeGuM",
      subject: "الأحياء",
      grade: "الصف الثالث الثانوي",
      teacherName: "أ. حسن محرم",
      period: "termBased",
      date: "2026-08-20",
      numberOfLessons: 14,
      price: 380,
      isFree: false,
      currency: "EGP",
      hasOffer: true,
      offerPercentage: "10% خصم",
      hasTimeLimit: false,
      isSplitToGroups: true,
      venue: "online",
      numberOfParticipants: 920,
      isDraft: false,
      sections: [
        {
          id: "sec-005",
          title: "الفصل الأول: التركيب الخلوي وDNA",
          isDraft: false,
          isLinkedToExam: true,
          linkedExamId: "exam-004", // FK → Exam.id
          isRequiredPassExamForNextSection: false,
          lessons: getSectionLessons("ar", "course-004", "sec-005"),
        },
      ],
    },
    {
      id: "course-005",
      coverImage: "/courses/arabic.jpg",
      title: "اللغة العربية - النحو والبلاغة الشاملة",
      description:
        "### الإتقان التام في قواعد النحو والبلاغة\n\nتهدف الدورة إلى تمكين طالب الثانوية العامة من **إعراب الجمل المعقدة** وفهم الصور البلاغية بمهارة عالية دون عناء.\n\n#### المنهجية الدراسية:\n- **قسم النحو**: دراسة الأفعال، الأسماء المرفوعة والمنصوبة والمجرورة، والممنوع من الصرف.\n- **قسم البلاغة**: علوم البيان والباديع والمعاني، وتذوق النصوص الأدبية.\n- **تدريبات النماذج الامتحان الشاملة**: حل أكثر من 500 سؤال اختيار من متعدد وتدريبات مقالية.\n\n> **ملاحظة:** يتم التقييم الأسبوعي عبر اختبارات إلكترونية تفاعلية تعطي النتائج والتحليلات فوراً.",
      previewVideoLink: "",
      subject: "اللغة العربية",
      grade: "الصف الثاني الثانوي",
      teacherName: "أ. وليد محسن",
      period: "monthly",
      date: "2026-09-10",
      numberOfLessons: 20,
      price: 250,
      isFree: false,
      currency: "EGP",
      hasOffer: false,
      hasTimeLimit: false,
      isSplitToGroups: false,
      venue: "center",
      numberOfParticipants: 1100,
      isDraft: false,
      sections: [],
    },
  ],
  en: [
    {
      id: "course-001",
      coverImage: "/courses/physics.jpg",
      title: "High School Physics - Full First Term Curriculum",
      description:
        "### About High School Physics Course\n\nThis course is the *complete guide* for **3rd Secondary** students in 1st Term Physics. Content is prepared to cover all curriculum parts with deep understanding.\n\n#### Methodological Goals:\n1. **Mastering Core Concepts**: Understanding electrical circuits, charges, and potential difference.\n2. **Solving Advanced Problems**: Practice on past exam questions and innovative thinking.\n3. **Practical Application**: Linking theoretical laws to real-life applications and lab experiments.\n\n#### Detailed Curriculum Units:\n- **Electric Current & Ohm's Law**: Intensity, resistivity $R = \\rho \\frac{L}{A}$, series & parallel connections.\n- **Kirchhoff's Laws**: Solving complex circuits using Charge Conservation and Energy Conservation.\n- **Magnetic Field & Magnetic Force**: Determining field directions and calculating magnetic dipole moment.\n\n> **Study Tip:** Solve interactive questions after every lesson to reinforce information.",
      previewVideoLink: "https://www.youtube.com/watch?v=u31qwQUeGuM",
      subject: "Physics",
      grade: "3rd Secondary",
      teacherName: "Mr. Mohamed Abdel Maaboud",
      period: "termBased",
      date: "2026-09-01",
      numberOfLessons: 18,
      price: 450,
      isFree: false,
      currency: "EGP",
      hasOffer: true,
      offerPercentage: "15% OFF",
      hasTimeLimit: true,
      timeLimitValue: 30,
      isSplitToGroups: true,
      venue: "all",
      numberOfParticipants: 1250,
      isDraft: false,
      sections: [
        {
          id: "sec-001",
          title: "Chapter 1: Electric Current, Ohm's Law & Kirchhoff's Laws",
          isDraft: false,
          isLinkedToExam: true,
          linkedExamId: "exam-001", // FK → Exam.id
          isRequiredPassExamForNextSection: true,
          lessons: getSectionLessons("en", "course-001", "sec-001"),
        },
        {
          id: "sec-002",
          title: "Chapter 2: Magnetic Effect of Electric Current & Measuring Devices",
          isDraft: false,
          isLinkedToExam: false,
          isRequiredPassExamForNextSection: false,
          lessons: getSectionLessons("en", "course-001", "sec-002"),
        },
      ],
    },
    {
      id: "course-002",
      coverImage: "/courses/chemistry.jpg",
      title: "Organic Chemistry Mastery",
      description:
        "### Course & Curriculum Details\n\n**Organic Chemistry** is one of the most vital branches for high school students. This course provides a step-by-step methodology for every reaction.\n\n#### Expected Learning Outcomes:\n- Master organic compound naming using the **IUPAC system**.\n- Understand reaction mechanisms such as *addition, substitution, and redox*.\n- Differentiate between functional groups and their physical and chemical properties.\n\n```text\nAlkane Halogenation (Example):\nCH4 + Cl2 --(UV Light)--> CH3Cl + HCl\n```\n\n#### Core Topics Agenda:\n1. **Alkanes, Alkenes & Alkynes**: Aliphatic Hydrocarbons.\n2. **Aromatic Benzene**: Aromatic Hydrocarbons and Substitution Reactions.\n3. **Hydrocarbon Derivatives**: Alcohols, Phenols, Ethers, and Carboxylic Acids.",
      previewVideoLink: "https://www.youtube.com/watch?v=u31qwQUeGuM",
      subject: "Chemistry",
      grade: "3rd Secondary",
      teacherName: "Dr. Ihab Abdelaziz",
      period: "monthly",
      date: "2026-09-15",
      numberOfLessons: 12,
      price: 200,
      isFree: false,
      currency: "EGP",
      hasOffer: false,
      hasTimeLimit: false,
      isSplitToGroups: false,
      venue: "online",
      numberOfParticipants: 850,
      isDraft: false,
      sections: [
        {
          id: "sec-003",
          title: "Chapter 1: Aliphatic Hydrocarbons & Nomenclature",
          isDraft: false,
          isLinkedToExam: true,
          linkedExamId: "exam-002", // FK → Exam.id
          isRequiredPassExamForNextSection: false,
          lessons: getSectionLessons("en", "course-002", "sec-003"),
        },
      ],
    },
    {
      id: "course-003",
      coverImage: "/courses/math.jpg",
      title: "Mathematics Fundamentals & Geometry",
      description:
        "### Free Foundation Course for 1st Secondary Students\n\nBuild a *solid mathematical foundation* enabling students to excel across high school stages.\n\n#### Course Content:\n- **Algebra Unit**: Relations & Functions, Discriminant of Quadratic Equations, Sequences.\n- **Geometry Unit**: Polygon & Triangle Similarity, Thales' Theorem, Tangents.\n- **Trigonometry**: Directed Angles, Circular & Sexagesimal Measurement, Basic Trigonometric Functions.",
      previewVideoLink: "",
      subject: "Mathematics",
      grade: "1st Secondary",
      teacherName: "Mr. Ahmed Sroor",
      period: "yearly",
      date: "2026-10-01",
      numberOfLessons: 6,
      price: 0,
      isFree: true,
      currency: "EGP",
      hasOffer: false,
      hasTimeLimit: true,
      timeLimitValue: 14,
      isSplitToGroups: false,
      venue: "center",
      numberOfParticipants: 3200,
      isDraft: true,
      sections: [
        {
          id: "sec-004",
          title: "Chapter 1: Triangle & Polygon Similarity",
          isDraft: false,
          isLinkedToExam: true,
          linkedExamId: "exam-003", // FK → Exam.id
          isRequiredPassExamForNextSection: false,
          lessons: getSectionLessons("en", "course-003", "sec-004"),
        },
      ],
    },
    {
      id: "course-004",
      coverImage: "/courses/biology.webp",
      title: "High School Biology & Genetics",
      description:
        "### Biology & Genetic Structure Guide\n\nBiology relies on visual understanding and linking vital functions to cellular structure.\n\n#### Key Discussion Points:\n- **Cellular & Molecular Structure**: Nucleus, Chromosomes, and DNA.\n- **DNA Replication & Protein Synthesis**: Replication mechanics, RNA role, and enzyme types.\n- **Genetic Engineering**: Biotechnology applications, Human Genome, and Restriction Enzymes.",
      previewVideoLink: "https://www.youtube.com/watch?v=u31qwQUeGuM",
      subject: "Biology",
      grade: "3rd Secondary",
      teacherName: "Mr. Hassan Mohram",
      period: "termBased",
      date: "2026-08-20",
      numberOfLessons: 14,
      price: 380,
      isFree: false,
      currency: "EGP",
      hasOffer: true,
      offerPercentage: "10% OFF",
      hasTimeLimit: false,
      isSplitToGroups: true,
      venue: "online",
      numberOfParticipants: 920,
      isDraft: false,
      sections: [
        {
          id: "sec-005",
          title: "Chapter 1: Cellular Structure & DNA",
          isDraft: false,
          isLinkedToExam: true,
          linkedExamId: "exam-004", // FK → Exam.id
          isRequiredPassExamForNextSection: false,
          lessons: getSectionLessons("en", "course-004", "sec-005"),
        },
      ],
    },
    {
      id: "course-005",
      coverImage: "/courses/arabic.jpg",
      title: "Arabic Language - Comprehensive Grammar & Rhetoric",
      description:
        "### Full Mastery in Grammar Rules & Rhetoric\n\nEmpowering high school students to parse complex sentences and understand rhetorical devices with ease.",
      previewVideoLink: "",
      subject: "Arabic",
      grade: "2nd Secondary",
      teacherName: "Mr. Waleed Mohsen",
      period: "monthly",
      date: "2026-09-10",
      numberOfLessons: 20,
      price: 250,
      isFree: false,
      currency: "EGP",
      hasOffer: false,
      hasTimeLimit: false,
      isSplitToGroups: false,
      venue: "center",
      numberOfParticipants: 1100,
      isDraft: false,
      sections: [],
    },
  ],
};
