import { Lesson } from "@/types/course";

export const mockLessonsData: Record<"ar" | "en", Lesson[]> = {
  ar: [
    {
      id: "les-001",
      type: "videoAndText",
      title: "الدرس الأول: شدة التيار الكهربي وفرق الجهد",
      description:
        "### ملخص الدرس الأول في الفيزياء\n\nتتناول هذه الجلسة شرحاً مفصلاً لـ **شدة التيار الكهربي** وقانون فرق الجهد عبر الموصلات.\n\n- حساب الشحنة الكهربية $Q = I \\cdot t$\n- قانون أوم وتطبيقاته العملية",
      coverImage: "/courses/physics.jpg",
      lectureVideoLink: "https://www.youtube.com/watch?v=u31qwQUeGuM",
      writtenText:
        "مفهوم الشحنة الكهربية وحركتها داخل الموصلات، وحساب شدة التيار وفرق الجهد الكهربي.",
      grade: "grade3",
      subject: "physics",
      teacherName: "أ. محمد عبد المعبود",
      hasPdfAttachments: true,
      pdfFiles: [
        {
          id: "att-001",
          title: "ملخص قوانين التيار الكهربي.pdf",
          fileUrl: "/assets/docs/physics_summary.pdf",
          fileType: "pdf",
          sizeInBytes: 2450000,
        },
      ],
      hasImageAttachments: true,
      imageFiles: [
        {
          id: "att-img-01",
          title: "رسم تبياني للدوائر الكهربية",
          fileUrl: "/courses/physics.jpg",
          fileType: "image",
        },
      ],
      isLinkedToExam: true,
      linkedExamId: "exam-001",
      linkedExamTitle: "امتحان شامل على التيار الكهربي وقانون أوم",
      isRequiredPassExam: true,
      venue: "all",
      lessonCategory: "course-dependent",
      courseId: "course-001",
      courseIds: ["course-001", "course-003"],
      courseTitle: "الفيزياء للثانوية العامة - منهج الترم الأول كامل",
      sectionId: "sec-001",
      publishStatus: "published",
      coursesCount: 2,
      viewsCount: 1842,
    },
    {
      id: "les-002",
      type: "videoAndText",
      title: "الدرس الثاني: المقاومة الكهربية وقانون أوم للدائرة المغلقة",
      description:
        "دراسة تفصيلية لتأثير طول الموصل ونوع المادة والمقاومة النوعية والتأثير الحراري على التيار الكهربي وقانون أوم للدائرة المغلقة.",
      coverImage: "/courses/physics.jpg",
      lectureVideoLink: "https://www.youtube.com/watch?v=u31qwQUeGuM",
      writtenText:
        "تأثير طول الموصل ومساحة المقطع ونوع المادة على المقاومة الكهربية، وقانون أوم للدائرة المغلقة.",
      grade: "grade3",
      subject: "physics",
      teacherName: "أ. محمد عبد المعبود",
      hasPdfAttachments: true,
      pdfFiles: [
        {
          id: "att-002",
          title: "تمارين قانون أوم للدائرة المغلقة.pdf",
          fileUrl: "/assets/docs/physics_summary.pdf",
          fileType: "pdf",
          sizeInBytes: 1800000,
        },
      ],
      hasImageAttachments: false,
      imageFiles: [],
      isLinkedToExam: false,
      venue: "online",
      lessonCategory: "course-dependent",
      courseId: "course-001",
      courseIds: ["course-001"],
      courseTitle: "الفيزياء للثانوية العامة - منهج الترم الأول كامل",
      sectionId: "sec-001",
      publishStatus: "published",
      coursesCount: 1,
      viewsCount: 976,
    },
    {
      id: "les-003",
      type: "text",
      title: "الدرس الثالث: قانونا كيرشوف وتطبيقاتهما (ملخص قراءة)",
      description:
        "### تطبيقات كيرشوف المتقدمة\n\nتطبيق قانون كيرشوف الأول (حفظ الشحنة) وقانون كيرشوف الثاني (حفظ الطاقة) على الدوائر الكهربية المعقدة وحسابات الجهد في المسارات المغلقة.",
      coverImage: "/courses/physics.jpg",
      writtenText:
        "تطبيق قانون كيرشوف الأول (حفظ الشحنة) وقانون كيرشوف الثاني (حفظ الطاقة) على الدوائر المعقدة.",
      grade: "grade3",
      subject: "physics",
      teacherName: "أ. محمد عبد المعبود",
      hasPdfAttachments: false,
      pdfFiles: [],
      hasImageAttachments: false,
      imageFiles: [],
      isLinkedToExam: false,
      venue: "all",
      lessonCategory: "course-dependent",
      courseId: "course-001",
      courseIds: ["course-001"],
      courseTitle: "الفيزياء للثانوية العامة - منهج الترم الأول كامل",
      sectionId: "sec-001",
      publishStatus: "published",
      coursesCount: 1,
      viewsCount: 654,
    },
    {
      id: "les-004",
      type: "videoAndText",
      title: "الدرس الأول: المجال المغناطيسي لتيار يمر في سلك مستقيم وملف دائري",
      description:
        "حساب كثافة الفيض المغناطيسي وقواعد تحديد اتجاه المجال المغناطيسي حول السلك والملف الدائري.",
      coverImage: "/courses/physics.jpg",
      lectureVideoLink: "https://www.youtube.com/watch?v=u31qwQUeGuM",
      writtenText: "حساب كثافة الفيض المغناطيسي وقواعد تحديد اتجاه المجال المغناطيسي.",
      grade: "grade3",
      subject: "physics",
      teacherName: "أ. محمد عبد المعبود",
      hasPdfAttachments: false,
      venue: "all",
      lessonCategory: "course-dependent",
      courseId: "course-001",
      courseIds: ["course-001"],
      courseTitle: "الفيزياء للثانوية العامة - منهج الترم الأول كامل",
      sectionId: "sec-002",
      publishStatus: "published",
      coursesCount: 1,
      viewsCount: 523,
    },
    {
      id: "les-005",
      type: "videoAndText",
      title: "الدرس الثاني: القوة المغناطيسية وعزم الثنائي قطب",
      description:
        "القوة المؤثرة على سلك يحمل تياراً موضوع في مجال مغناطيسي وعزم الازدواج المؤثر على ملف.",
      coverImage: "/courses/physics.jpg",
      lectureVideoLink: "https://www.youtube.com/watch?v=u31qwQUeGuM",
      writtenText: "القوة المؤثرة على سلك يحمل تياراً موضوع في مجال مغناطيسي وعزم الازدواج.",
      grade: "grade3",
      subject: "physics",
      teacherName: "أ. محمد عبد المعبود",
      hasPdfAttachments: false,
      venue: "all",
      lessonCategory: "course-dependent",
      courseId: "course-001",
      courseIds: ["course-001"],
      courseTitle: "الفيزياء للثانوية العامة - منهج الترم الأول كامل",
      sectionId: "sec-002",
      publishStatus: "published",
      coursesCount: 1,
      viewsCount: 389,
    },
    {
      id: "les-006",
      type: "videoAndText",
      title: "الدرس الأول: مقدمة في الكيمياء العضوية والألكانات",
      description:
        "دراسة المركبات العضوية والهيدروكربونات وتسمية الألكانات حسب نظام IUPAC العالمي.",
      coverImage: "/courses/chemistry.jpg",
      lectureVideoLink: "https://www.youtube.com/watch?v=u31qwQUeGuM",
      writtenText: "المركبات العضوية والهيدروكربونات وتسمية الألكانات حسب نظام IUPAC.",
      grade: "grade3",
      subject: "chemistry",
      teacherName: "د. إيهاب عبد العزيز",
      venue: "online",
      lessonCategory: "course-dependent",
      courseId: "course-002",
      courseIds: ["course-002", "course-004"],
      courseTitle: "الكيمياء العضوية والتفوق فيها",
      sectionId: "sec-003",
      publishStatus: "published",
      coursesCount: 2,
      viewsCount: 712,
    },
    {
      id: "les-007",
      type: "videoAndText",
      title: "الدرس الثاني: الألكينات والألكاينات والتفاعلات",
      description: "الهيدروكربونات غير المشبعة وتفاعلات الإضافة وقاعدة ماركونيكوف وكيفية تطبيقها.",
      coverImage: "/courses/chemistry.jpg",
      lectureVideoLink: "https://www.youtube.com/watch?v=u31qwQUeGuM",
      writtenText: "الهيدروكربونات غير المشبعة وتفاعلات الإضافة وقاعدة ماركونيكوف.",
      grade: "grade3",
      subject: "chemistry",
      teacherName: "د. إيهاب عبد العزيز",
      venue: "online",
      lessonCategory: "course-dependent",
      courseId: "course-002",
      courseIds: ["course-002"],
      courseTitle: "الكيمياء العضوية والتفوق فيها",
      sectionId: "sec-003",
      publishStatus: "draft",
      coursesCount: 1,
      viewsCount: 0,
    },
    {
      id: "les-008",
      type: "text",
      title: "الدرس الأول: شروط تشابه مضلعين وتطبيقات عملية",
      description:
        "مفهوم التناسب بين الأضلاع المتناظرة وتساوي الزوايا المتناظرة في المضلعات والمثلثات المتشابهة.",
      coverImage: "/courses/math.jpg",
      writtenText: "مفهوم التناسب بين الأضلاع وتساوي الزوايا المتناظرة في المضلعات المتشابهة.",
      grade: "grade1",
      subject: "mathematics",
      teacherName: "أ. أحمد سرور",
      venue: "center",
      lessonCategory: "course-dependent",
      courseId: "course-003",
      courseIds: ["course-003"],
      courseTitle: "أساسيات الرياضيات والفرع الهندسي",
      sectionId: "sec-004",
      publishStatus: "published",
      coursesCount: 1,
      viewsCount: 445,
    },
    {
      id: "les-009",
      type: "videoAndText",
      title: "الدرس الأول: تركيب الحمض النووي DNA وتضاعفه",
      description:
        "شرح نموذج واتسون وكرك لتركيب الشريط المزدوج وتضاعف DNA باستخدام أنزيما التضاعف والربط.",
      coverImage: "/courses/biology.webp",
      lectureVideoLink: "https://www.youtube.com/watch?v=u31qwQUeGuM",
      writtenText: "شرح نموذج واتسون وكرك وتضاعف DNA وأنزيما التضاعف والربط.",
      grade: "grade3",
      subject: "biology",
      teacherName: "أ. حسن محرم",
      venue: "online",
      lessonCategory: "course-dependent",
      courseId: "course-004",
      courseIds: ["course-004"],
      courseTitle: "الأحياء والوراثة للثانوية العامة",
      sectionId: "sec-005",
      publishStatus: "published",
      coursesCount: 1,
      viewsCount: 1203,
    },
    {
      id: "les-standalone-010",
      type: "text",
      title: "محاضرة مستقلة: استراتيجيات تفوق الثانوية العامة",
      description:
        "### دليل الاستراتيجيات الشاملة\n\nقراءة متخصصة ومستقلة تقدم نصائح تنظيم الوقت وإدارة امتحانات الثانوية العامة بأسلوب عملي ومتكامل.",
      coverImage: "/courses/arabic.jpg",
      grade: "grade3",
      subject: "arabic",
      teacherName: "د. سامح إبراهيم",
      hasPdfAttachments: true,
      pdfFiles: [
        {
          id: "att-pdf-10",
          title: "دليل الاستراتيجيات والامتحانات.pdf",
          fileUrl: "/assets/docs/chemistry_guide.pdf",
          fileType: "pdf",
          sizeInBytes: 3100000,
        },
      ],
      venue: "center",
      lessonCategory: "independent",
      courseIds: ["course-001", "course-002", "course-005"],
      coursesCount: 3,
      publishStatus: "published",
      viewsCount: 3271,
    },
  ],
  en: [
    {
      id: "les-001",
      type: "videoAndText",
      title: "Lesson 1: Electric Current Intensity & Potential Difference",
      description:
        "### Physics Lesson 1 Overview\n\nComprehensive explanation of **electric current intensity** and potential difference formula across conductors.\n\n- Electric charge formula $Q = I \\cdot t$\n- Ohm's Law and practical applications",
      coverImage: "/courses/physics.jpg",
      lectureVideoLink: "https://www.youtube.com/watch?v=u31qwQUeGuM",
      writtenText:
        "Concept of electric charge movement inside conductors and calculating current intensity and voltage.",
      grade: "grade3",
      subject: "physics",
      teacherName: "Mr. Mohamed Abdel Maaboud",
      hasPdfAttachments: true,
      pdfFiles: [
        {
          id: "att-001",
          title: "Electric_Current_Laws_Summary.pdf",
          fileUrl: "/assets/docs/physics_summary.pdf",
          fileType: "pdf",
          sizeInBytes: 2450000,
        },
      ],
      hasImageAttachments: true,
      imageFiles: [
        {
          id: "att-img-01",
          title: "Electrical Circuits Diagram",
          fileUrl: "/courses/physics.jpg",
          fileType: "image",
        },
      ],
      isLinkedToExam: true,
      linkedExamId: "exam-001",
      linkedExamTitle: "Comprehensive Exam on Electric Current & Ohm's Law",
      isRequiredPassExam: true,
      venue: "all",
      lessonCategory: "course-dependent",
      courseId: "course-001",
      courseIds: ["course-001", "course-003"],
      courseTitle: "High School Physics - Full First Term Curriculum",
      sectionId: "sec-001",
      publishStatus: "published",
      coursesCount: 2,
      viewsCount: 1842,
    },
    {
      id: "les-002",
      type: "videoAndText",
      title: "Lesson 2: Electrical Resistance & Ohm's Law for Closed Circuits",
      description:
        "Detailed study of conductor length, cross-sectional area, resistivity, temperature effect, and Ohm's Law for closed circuits.",
      coverImage: "/courses/physics.jpg",
      lectureVideoLink: "https://www.youtube.com/watch?v=u31qwQUeGuM",
      writtenText:
        "Effect of conductor length, cross-sectional area, and material type on electrical resistance.",
      grade: "grade3",
      subject: "physics",
      teacherName: "Mr. Mohamed Abdel Maaboud",
      hasPdfAttachments: true,
      pdfFiles: [
        {
          id: "att-002",
          title: "Closed_Circuit_Ohms_Law_Exercises.pdf",
          fileUrl: "/assets/docs/physics_summary.pdf",
          fileType: "pdf",
          sizeInBytes: 1800000,
        },
      ],
      hasImageAttachments: false,
      imageFiles: [],
      isLinkedToExam: false,
      venue: "online",
      lessonCategory: "course-dependent",
      courseId: "course-001",
      courseIds: ["course-001"],
      courseTitle: "High School Physics - Full First Term Curriculum",
      sectionId: "sec-001",
      publishStatus: "published",
      coursesCount: 1,
      viewsCount: 976,
    },
    {
      id: "les-003",
      type: "text",
      title: "Lesson 3: Kirchhoff's Laws and Applications (Reading Summary)",
      description:
        "### Advanced Kirchhoff Applications\n\nApplying Kirchhoff's 1st Law (Charge Conservation) and 2nd Law (Energy Conservation) to complex electrical loops.",
      coverImage: "/courses/physics.jpg",
      writtenText: "Applying Kirchhoff's 1st Law and 2nd Law to complex electrical networks.",
      grade: "grade3",
      subject: "physics",
      teacherName: "Mr. Mohamed Abdel Maaboud",
      hasPdfAttachments: false,
      pdfFiles: [],
      hasImageAttachments: false,
      imageFiles: [],
      isLinkedToExam: false,
      venue: "all",
      lessonCategory: "course-dependent",
      courseId: "course-001",
      courseIds: ["course-001"],
      courseTitle: "High School Physics - Full First Term Curriculum",
      sectionId: "sec-001",
      publishStatus: "published",
      coursesCount: 1,
      viewsCount: 654,
    },
    {
      id: "les-004",
      type: "videoAndText",
      title: "Lesson 1: Magnetic Field of Straight Wire & Circular Loop",
      description:
        "Calculating magnetic flux density and rules for determining magnetic field direction around straight conductors and circular loops.",
      coverImage: "/courses/physics.jpg",
      lectureVideoLink: "https://www.youtube.com/watch?v=u31qwQUeGuM",
      writtenText: "Calculating magnetic flux density and field direction rules.",
      grade: "grade3",
      subject: "physics",
      teacherName: "Mr. Mohamed Abdel Maaboud",
      hasPdfAttachments: false,
      venue: "all",
      lessonCategory: "course-dependent",
      courseId: "course-001",
      courseIds: ["course-001"],
      courseTitle: "High School Physics - Full First Term Curriculum",
      sectionId: "sec-002",
      publishStatus: "published",
      coursesCount: 1,
      viewsCount: 523,
    },
    {
      id: "les-005",
      type: "videoAndText",
      title: "Lesson 2: Magnetic Force & Dipole Moment",
      description:
        "Force acting on a current-carrying conductor in a magnetic field and torque on a coil.",
      coverImage: "/courses/physics.jpg",
      lectureVideoLink: "https://www.youtube.com/watch?v=u31qwQUeGuM",
      writtenText: "Magnetic force acting on a wire and torque moment on a coil.",
      grade: "grade3",
      subject: "physics",
      teacherName: "Mr. Mohamed Abdel Maaboud",
      hasPdfAttachments: false,
      venue: "all",
      lessonCategory: "course-dependent",
      courseId: "course-001",
      courseIds: ["course-001"],
      courseTitle: "High School Physics - Full First Term Curriculum",
      sectionId: "sec-002",
      publishStatus: "published",
      coursesCount: 1,
      viewsCount: 389,
    },
    {
      id: "les-006",
      type: "videoAndText",
      title: "Lesson 1: Intro to Organic Chemistry & Alkanes",
      description:
        "Study of organic compounds, hydrocarbons, and alkane nomenclature following the IUPAC system.",
      coverImage: "/courses/chemistry.jpg",
      lectureVideoLink: "https://www.youtube.com/watch?v=u31qwQUeGuM",
      writtenText: "Organic compounds, hydrocarbons, and IUPAC alkane naming.",
      grade: "grade3",
      subject: "chemistry",
      teacherName: "Dr. Ihab Abdelaziz",
      venue: "online",
      lessonCategory: "course-dependent",
      courseId: "course-002",
      courseIds: ["course-002", "course-004"],
      courseTitle: "Organic Chemistry Mastery",
      sectionId: "sec-003",
      publishStatus: "published",
      coursesCount: 2,
      viewsCount: 712,
    },
    {
      id: "les-007",
      type: "videoAndText",
      title: "Lesson 2: Alkenes, Alkynes & Chemical Reactions",
      description:
        "Unsaturated hydrocarbons, addition reactions, and Markovnikov's rule application.",
      coverImage: "/courses/chemistry.jpg",
      lectureVideoLink: "https://www.youtube.com/watch?v=u31qwQUeGuM",
      writtenText: "Unsaturated hydrocarbons and addition reactions.",
      grade: "grade3",
      subject: "chemistry",
      teacherName: "Dr. Ihab Abdelaziz",
      venue: "online",
      lessonCategory: "course-dependent",
      courseId: "course-002",
      courseIds: ["course-002"],
      courseTitle: "Organic Chemistry Mastery",
      sectionId: "sec-003",
      publishStatus: "draft",
      coursesCount: 1,
      viewsCount: 0,
    },
    {
      id: "les-008",
      type: "text",
      title: "Lesson 1: Conditions for Polygon Similarity & Applications",
      description:
        "Proportionality of corresponding sides and equality of corresponding angles in similar polygons and triangles.",
      coverImage: "/courses/math.jpg",
      writtenText: "Side proportionality and angle equality in similar polygons.",
      grade: "grade1",
      subject: "mathematics",
      teacherName: "Mr. Ahmed Sroor",
      venue: "center",
      lessonCategory: "course-dependent",
      courseId: "course-003",
      courseIds: ["course-003"],
      courseTitle: "Mathematics Fundamentals & Geometry",
      sectionId: "sec-004",
      publishStatus: "published",
      coursesCount: 1,
      viewsCount: 445,
    },
    {
      id: "les-009",
      type: "videoAndText",
      title: "Lesson 1: DNA Structure & Replication",
      description:
        "Explanation of the Watson-Crick double helix model and DNA replication process using enzymes.",
      coverImage: "/courses/biology.webp",
      lectureVideoLink: "https://www.youtube.com/watch?v=u31qwQUeGuM",
      writtenText: "Watson-Crick model and DNA replication mechanisms.",
      grade: "grade3",
      subject: "biology",
      teacherName: "Mr. Hassan Mohram",
      venue: "online",
      lessonCategory: "course-dependent",
      courseId: "course-004",
      courseIds: ["course-004"],
      courseTitle: "High School Biology & Genetics",
      sectionId: "sec-005",
      publishStatus: "published",
      coursesCount: 1,
      viewsCount: 1203,
    },
    {
      id: "les-standalone-010",
      type: "text",
      title: "Independent Lecture: Exam Strategies & Study Tips",
      description:
        "### Comprehensive Study Guide\n\nIndependent advice and time management strategies for high school final examinations.",
      coverImage: "/courses/arabic.jpg",
      grade: "grade3",
      subject: "arabic",
      teacherName: "Dr. Sameh Ibrahim",
      hasPdfAttachments: true,
      pdfFiles: [
        {
          id: "att-pdf-10",
          title: "Exam_Strategies_Guide.pdf",
          fileUrl: "/assets/docs/chemistry_guide.pdf",
          fileType: "pdf",
          sizeInBytes: 3100000,
        },
      ],
      venue: "center",
      lessonCategory: "independent",
      courseIds: ["course-001", "course-002", "course-005"],
      coursesCount: 3,
      publishStatus: "published",
      viewsCount: 3271,
    },
  ],
};
