import { Student } from "@/types/student";

export const mockStudentsData: { ar: Student[]; en: Student[] } = {
  ar: [
    {
      id: "std-1",
      firstName: "أحمد",
      middleName: "محمد",
      lastName: "علي",
      additionalName: "حسن",
      phoneNumber: "+201012345678",
      parentPhoneNumber: "+201098765432",
      gender: "male",
      email: "ahmed.ali@example.com",
      password: "password123",
      country: "مصر",
      state: "القاهرة",
      grade: "grade3",
      registrationType: "center",
      coursesCount: 4,
      balance: 350,
      averageRating: 3.85,
      gpa: "3.85 / 4.0",
      status: "active",
      createdAt: "2026-01-15T10:00:00Z",
    },
    {
      id: "std-2",
      firstName: "سارة",
      middleName: "محمود",
      lastName: "إبراهيم",
      additionalName: "",
      phoneNumber: "+201123456789",
      parentPhoneNumber: "+201187654321",
      gender: "female",
      email: "sara.ibrahim@example.com",
      password: "password123",
      country: "مصر",
      state: "الأسكندرية",
      grade: "grade2",
      registrationType: "online",
      coursesCount: 2,
      balance: 150,
      averageRating: 3.95,
      gpa: "3.95 / 4.0",
      status: "active",
      createdAt: "2026-02-01T12:30:00Z",
    },
    {
      id: "std-3",
      firstName: "عمر",
      middleName: "خالد",
      lastName: "يوسف",
      additionalName: "الخولي",
      phoneNumber: "+201234567890",
      parentPhoneNumber: "+201276543210",
      gender: "male",
      email: "omar.youssef@example.com",
      password: "password123",
      country: "مصر",
      state: "الجيزة",
      grade: "grade1",
      registrationType: "hybrid",
      coursesCount: 5,
      balance: 0,
      averageRating: 3.4,
      gpa: "3.40 / 4.0",
      status: "suspended",
      createdAt: "2026-02-10T15:45:00Z",
    },
    {
      id: "std-4",
      firstName: "مريم",
      middleName: "أحمد",
      lastName: "سامي",
      additionalName: "",
      phoneNumber: "+201005556677",
      parentPhoneNumber: "+201009998877",
      gender: "female",
      email: "maryam.samy@example.com",
      password: "password123",
      country: "مصر",
      state: "الشرقية",
      grade: "grade3",
      registrationType: "external",
      coursesCount: 1,
      balance: 500,
      averageRating: 3.75,
      gpa: "3.75 / 4.0",
      status: "active",
      createdAt: "2026-02-18T09:20:00Z",
    },
    {
      id: "std-5",
      firstName: "يوسف",
      middleName: "طارق",
      lastName: "مصطفى",
      additionalName: "السيد",
      phoneNumber: "+201501112233",
      parentPhoneNumber: "+201504445566",
      gender: "male",
      email: "youssef.mustafa@example.com",
      password: "password123",
      country: "السعودية",
      state: "الرياض",
      grade: "grade3",
      registrationType: "online",
      coursesCount: 3,
      balance: 200,
      averageRating: 3.6,
      gpa: "3.60 / 4.0",
      status: "active",
      createdAt: "2026-03-01T11:15:00Z",
    },
    {
      id: "std-6",
      firstName: "نور",
      middleName: "هشام",
      lastName: "عبد الفتاح",
      additionalName: "",
      phoneNumber: "+201198887766",
      parentPhoneNumber: "+201133332211",
      gender: "female",
      email: "nour.hisham@example.com",
      password: "password123",
      country: "مصر",
      state: "القاهرة",
      grade: "grade2",
      registrationType: "center",
      coursesCount: 6,
      balance: 750,
      averageRating: 4.0,
      gpa: "4.00 / 4.0",
      status: "active",
      createdAt: "2026-03-05T14:10:00Z",
    },
    {
      id: "std-7",
      firstName: "كريم",
      middleName: "شريف",
      lastName: "منصور",
      additionalName: "",
      phoneNumber: "+201044443322",
      parentPhoneNumber: "+201077778899",
      gender: "male",
      email: "karim.mansour@example.com",
      password: "password123",
      country: "الإمارات",
      state: "دبي",
      grade: "grade1",
      registrationType: "online",
      coursesCount: 2,
      balance: 100,
      averageRating: 3.2,
      gpa: "3.20 / 4.0",
      status: "active",
      createdAt: "2026-03-12T16:00:00Z",
    },
  ],
  en: [
    {
      id: "std-1",
      firstName: "Ahmed",
      middleName: "Mohamed",
      lastName: "Ali",
      additionalName: "Hassan",
      phoneNumber: "+201012345678",
      parentPhoneNumber: "+201098765432",
      gender: "male",
      email: "ahmed.ali@example.com",
      password: "password123",
      country: "Egypt",
      state: "Cairo",
      grade: "grade3",
      registrationType: "center",
      coursesCount: 4,
      balance: 350,
      averageRating: 3.85,
      gpa: "3.85 / 4.0",
      status: "active",
      createdAt: "2026-01-15T10:00:00Z",
    },
    {
      id: "std-2",
      firstName: "Sara",
      middleName: "Mahmoud",
      lastName: "Ibrahim",
      additionalName: "",
      phoneNumber: "+201123456789",
      parentPhoneNumber: "+201187654321",
      gender: "female",
      email: "sara.ibrahim@example.com",
      password: "password123",
      country: "Egypt",
      state: "Alexandria",
      grade: "grade2",
      registrationType: "online",
      coursesCount: 2,
      balance: 150,
      averageRating: 3.95,
      gpa: "3.95 / 4.0",
      status: "active",
      createdAt: "2026-02-01T12:30:00Z",
    },
    {
      id: "std-3",
      firstName: "Omar",
      middleName: "Khaled",
      lastName: "Youssef",
      additionalName: "Elkhouly",
      phoneNumber: "+201234567890",
      parentPhoneNumber: "+201276543210",
      gender: "male",
      email: "omar.youssef@example.com",
      password: "password123",
      country: "Egypt",
      state: "Giza",
      grade: "grade1",
      registrationType: "hybrid",
      coursesCount: 5,
      balance: 0,
      averageRating: 3.4,
      gpa: "3.40 / 4.0",
      status: "suspended",
      createdAt: "2026-02-10T15:45:00Z",
    },
    {
      id: "std-4",
      firstName: "Maryam",
      middleName: "Ahmed",
      lastName: "Samy",
      additionalName: "",
      phoneNumber: "+201005556677",
      parentPhoneNumber: "+201009998877",
      gender: "female",
      email: "maryam.samy@example.com",
      password: "password123",
      country: "Egypt",
      state: "Sharqia",
      grade: "grade3",
      registrationType: "external",
      coursesCount: 1,
      balance: 500,
      averageRating: 3.75,
      gpa: "3.75 / 4.0",
      status: "active",
      createdAt: "2026-02-18T09:20:00Z",
    },
    {
      id: "std-5",
      firstName: "Youssef",
      middleName: "Tarek",
      lastName: "Mustafa",
      additionalName: "Elsayed",
      phoneNumber: "+201501112233",
      parentPhoneNumber: "+201504445566",
      gender: "male",
      email: "youssef.mustafa@example.com",
      password: "password123",
      country: "Saudi Arabia",
      state: "Riyadh",
      grade: "grade3",
      registrationType: "online",
      coursesCount: 3,
      balance: 200,
      averageRating: 3.6,
      gpa: "3.60 / 4.0",
      status: "active",
      createdAt: "2026-03-01T11:15:00Z",
    },
    {
      id: "std-6",
      firstName: "Nour",
      middleName: "Hisham",
      lastName: "Abdel Fattah",
      additionalName: "",
      phoneNumber: "+201198887766",
      parentPhoneNumber: "+201133332211",
      gender: "female",
      email: "nour.hisham@example.com",
      password: "password123",
      country: "Egypt",
      state: "Cairo",
      grade: "grade2",
      registrationType: "center",
      coursesCount: 6,
      balance: 750,
      averageRating: 4.0,
      gpa: "4.00 / 4.0",
      status: "active",
      createdAt: "2026-03-05T14:10:00Z",
    },
    {
      id: "std-7",
      firstName: "Karim",
      middleName: "Sherif",
      lastName: "Mansour",
      additionalName: "",
      phoneNumber: "+201044443322",
      parentPhoneNumber: "+201077778899",
      gender: "male",
      email: "karim.mansour@example.com",
      password: "password123",
      country: "UAE",
      state: "Dubai",
      grade: "grade1",
      registrationType: "online",
      coursesCount: 2,
      balance: 100,
      averageRating: 3.2,
      gpa: "3.20 / 4.0",
      status: "active",
      createdAt: "2026-03-12T16:00:00Z",
    },
  ],
};
