# Step 1: Base image
FROM node:22-alpine AS base
# CRITICAL: Enable corepack to automatically manage pnpm versions
RUN corepack enable

# Step 2: Install dependencies
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
# Copy the pnpm lockfile instead of package-lock.json
COPY package.json pnpm-lock.yaml* ./
# Use --frozen-lockfile to ensure strictly reproducible builds
RUN pnpm install --frozen-lockfile

# Step 3: Build the source code
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

RUN pnpm run build

# Step 4: Production image, copy all the files and run next
FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Create a non-root user for security
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy the public folder
COPY --from=builder /app/public ./public

# Copy the standalone output generated by Next.js
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Run as the non-root user
USER nextjs

EXPOSE 3000
ENV PORT=3000
# Cloud Run needs the host set to 0.0.0.0
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]