/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiErrorResponseDto,
  AuthControllerGetProfile200,
  AuthControllerLogin200,
  AuthControllerLogout200,
  AuthControllerRegister201,
  AuthControllerResendVerification200,
  AuthControllerVerify200,
  LoginDto,
  MagicLinkControllerRequest200,
  MagicLinkControllerVerify200,
  RegisterDto,
  RequestMagicLinkDto,
  ResendVerificationDto,
  VerifyMagicLinkDto,
} from "../../../../types/api";

import { api } from "../../../apiClient";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Login with email and password
 */
export const authControllerLogin = (
  loginDto: LoginDto,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<AuthControllerLogin200>(
    {
      url: `http://localhost:8000/api/auth/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: loginDto,
      signal,
    },
    options,
  );
};

export const getAuthControllerLoginMutationOptions = <
  TError = ApiErrorResponseDto,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerLogin>>,
    TError,
    { data: LoginDto },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerLogin>>,
  TError,
  { data: LoginDto },
  TContext
> => {
  const mutationKey = ["authControllerLogin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerLogin>>,
    { data: LoginDto }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerLogin>>
>;
export type AuthControllerLoginMutationBody = LoginDto;
export type AuthControllerLoginMutationError = ApiErrorResponseDto;

/**
 * @summary Login with email and password
 */
export const useAuthControllerLogin = <TError = ApiErrorResponseDto, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerLogin>>,
      TError,
      { data: LoginDto },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerLogin>>,
  TError,
  { data: LoginDto },
  TContext
> => {
  return useMutation(getAuthControllerLoginMutationOptions(options), queryClient);
};
/**
 * @summary Logout the current user
 */
export const authControllerLogout = (
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<AuthControllerLogout200>(
    { url: `http://localhost:8000/api/auth/logout`, method: "POST", signal },
    options,
  );
};

export const getAuthControllerLogoutMutationOptions = <
  TError = ApiErrorResponseDto,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerLogout>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["authControllerLogout"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerLogout>>,
    void
  > = () => {
    return authControllerLogout(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerLogout>>
>;

export type AuthControllerLogoutMutationError = ApiErrorResponseDto;

/**
 * @summary Logout the current user
 */
export const useAuthControllerLogout = <TError = ApiErrorResponseDto, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerLogout>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof authControllerLogout>>, TError, void, TContext> => {
  return useMutation(getAuthControllerLogoutMutationOptions(options), queryClient);
};
/**
 * @summary Get current user profile
 */
export const authControllerGetProfile = (
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<AuthControllerGetProfile200>(
    { url: `http://localhost:8000/api/auth/me`, method: "GET", signal },
    options,
  );
};

export const getAuthControllerGetProfileQueryKey = () => {
  return [`http://localhost:8000/api/auth/me`] as const;
};

export const getAuthControllerGetProfileQueryOptions = <
  TData = Awaited<ReturnType<typeof authControllerGetProfile>>,
  TError = ApiErrorResponseDto,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof authControllerGetProfile>>, TError, TData>
  >;
  request?: SecondParameter<typeof api>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAuthControllerGetProfileQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerGetProfile>>> = ({
    signal,
  }) => authControllerGetProfile(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authControllerGetProfile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AuthControllerGetProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGetProfile>>
>;
export type AuthControllerGetProfileQueryError = ApiErrorResponseDto;

export function useAuthControllerGetProfile<
  TData = Awaited<ReturnType<typeof authControllerGetProfile>>,
  TError = ApiErrorResponseDto,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authControllerGetProfile>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGetProfile>>,
          TError,
          Awaited<ReturnType<typeof authControllerGetProfile>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAuthControllerGetProfile<
  TData = Awaited<ReturnType<typeof authControllerGetProfile>>,
  TError = ApiErrorResponseDto,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authControllerGetProfile>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGetProfile>>,
          TError,
          Awaited<ReturnType<typeof authControllerGetProfile>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAuthControllerGetProfile<
  TData = Awaited<ReturnType<typeof authControllerGetProfile>>,
  TError = ApiErrorResponseDto,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authControllerGetProfile>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get current user profile
 */

export function useAuthControllerGetProfile<
  TData = Awaited<ReturnType<typeof authControllerGetProfile>>,
  TError = ApiErrorResponseDto,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authControllerGetProfile>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAuthControllerGetProfileQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Register a new user
 */
export const authControllerRegister = (
  registerDto: RegisterDto,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<AuthControllerRegister201>(
    {
      url: `http://localhost:8000/api/auth/register`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: registerDto,
      signal,
    },
    options,
  );
};

export const getAuthControllerRegisterMutationOptions = <
  TError = ApiErrorResponseDto,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerRegister>>,
    TError,
    { data: RegisterDto },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerRegister>>,
  TError,
  { data: RegisterDto },
  TContext
> => {
  const mutationKey = ["authControllerRegister"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerRegister>>,
    { data: RegisterDto }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerRegister(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerRegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerRegister>>
>;
export type AuthControllerRegisterMutationBody = RegisterDto;
export type AuthControllerRegisterMutationError = ApiErrorResponseDto;

/**
 * @summary Register a new user
 */
export const useAuthControllerRegister = <TError = ApiErrorResponseDto, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerRegister>>,
      TError,
      { data: RegisterDto },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerRegister>>,
  TError,
  { data: RegisterDto },
  TContext
> => {
  return useMutation(getAuthControllerRegisterMutationOptions(options), queryClient);
};
/**
 * @summary Resend verification email
 */
export const authControllerResendVerification = (
  resendVerificationDto: ResendVerificationDto,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<AuthControllerResendVerification200>(
    {
      url: `http://localhost:8000/api/auth/resend-verification`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: resendVerificationDto,
      signal,
    },
    options,
  );
};

export const getAuthControllerResendVerificationMutationOptions = <
  TError = ApiErrorResponseDto,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerResendVerification>>,
    TError,
    { data: ResendVerificationDto },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerResendVerification>>,
  TError,
  { data: ResendVerificationDto },
  TContext
> => {
  const mutationKey = ["authControllerResendVerification"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerResendVerification>>,
    { data: ResendVerificationDto }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerResendVerification(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerResendVerificationMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerResendVerification>>
>;
export type AuthControllerResendVerificationMutationBody = ResendVerificationDto;
export type AuthControllerResendVerificationMutationError = ApiErrorResponseDto;

/**
 * @summary Resend verification email
 */
export const useAuthControllerResendVerification = <
  TError = ApiErrorResponseDto,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerResendVerification>>,
      TError,
      { data: ResendVerificationDto },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerResendVerification>>,
  TError,
  { data: ResendVerificationDto },
  TContext
> => {
  return useMutation(getAuthControllerResendVerificationMutationOptions(options), queryClient);
};
/**
 * @summary Login with Google OAuth2
 */
export const authControllerGoogleAuth = (
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<void>(
    { url: `http://localhost:8000/api/auth/google`, method: "GET", signal },
    options,
  );
};

export const getAuthControllerGoogleAuthQueryKey = () => {
  return [`http://localhost:8000/api/auth/google`] as const;
};

export const getAuthControllerGoogleAuthQueryOptions = <
  TData = Awaited<ReturnType<typeof authControllerGoogleAuth>>,
  TError = ApiErrorResponseDto,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleAuth>>, TError, TData>
  >;
  request?: SecondParameter<typeof api>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAuthControllerGoogleAuthQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerGoogleAuth>>> = ({
    signal,
  }) => authControllerGoogleAuth(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authControllerGoogleAuth>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AuthControllerGoogleAuthQueryResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGoogleAuth>>
>;
export type AuthControllerGoogleAuthQueryError = ApiErrorResponseDto;

export function useAuthControllerGoogleAuth<
  TData = Awaited<ReturnType<typeof authControllerGoogleAuth>>,
  TError = ApiErrorResponseDto,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleAuth>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGoogleAuth>>,
          TError,
          Awaited<ReturnType<typeof authControllerGoogleAuth>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAuthControllerGoogleAuth<
  TData = Awaited<ReturnType<typeof authControllerGoogleAuth>>,
  TError = ApiErrorResponseDto,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleAuth>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGoogleAuth>>,
          TError,
          Awaited<ReturnType<typeof authControllerGoogleAuth>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAuthControllerGoogleAuth<
  TData = Awaited<ReturnType<typeof authControllerGoogleAuth>>,
  TError = ApiErrorResponseDto,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleAuth>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Login with Google OAuth2
 */

export function useAuthControllerGoogleAuth<
  TData = Awaited<ReturnType<typeof authControllerGoogleAuth>>,
  TError = ApiErrorResponseDto,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleAuth>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAuthControllerGoogleAuthQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Google OAuth2 callback
 */
export const authControllerGoogleAuthRedirect = (
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<void>(
    { url: `http://localhost:8000/api/auth/google/callback`, method: "GET", signal },
    options,
  );
};

export const getAuthControllerGoogleAuthRedirectQueryKey = () => {
  return [`http://localhost:8000/api/auth/google/callback`] as const;
};

export const getAuthControllerGoogleAuthRedirectQueryOptions = <
  TData = Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>,
  TError = ApiErrorResponseDto,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>, TError, TData>
  >;
  request?: SecondParameter<typeof api>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAuthControllerGoogleAuthRedirectQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>> = ({
    signal,
  }) => authControllerGoogleAuthRedirect(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AuthControllerGoogleAuthRedirectQueryResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>
>;
export type AuthControllerGoogleAuthRedirectQueryError = ApiErrorResponseDto;

export function useAuthControllerGoogleAuthRedirect<
  TData = Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>,
  TError = ApiErrorResponseDto,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>,
          TError,
          Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAuthControllerGoogleAuthRedirect<
  TData = Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>,
  TError = ApiErrorResponseDto,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>,
          TError,
          Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAuthControllerGoogleAuthRedirect<
  TData = Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>,
  TError = ApiErrorResponseDto,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Google OAuth2 callback
 */

export function useAuthControllerGoogleAuthRedirect<
  TData = Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>,
  TError = ApiErrorResponseDto,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authControllerGoogleAuthRedirect>>, TError, TData>
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAuthControllerGoogleAuthRedirectQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Verify email token
 */
export const authControllerVerify = (
  verifyMagicLinkDto: VerifyMagicLinkDto,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<AuthControllerVerify200>(
    {
      url: `http://localhost:8000/api/auth/verify`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: verifyMagicLinkDto,
      signal,
    },
    options,
  );
};

export const getAuthControllerVerifyMutationOptions = <
  TError = ApiErrorResponseDto,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerVerify>>,
    TError,
    { data: VerifyMagicLinkDto },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerVerify>>,
  TError,
  { data: VerifyMagicLinkDto },
  TContext
> => {
  const mutationKey = ["authControllerVerify"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerVerify>>,
    { data: VerifyMagicLinkDto }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerVerify(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerVerifyMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerVerify>>
>;
export type AuthControllerVerifyMutationBody = VerifyMagicLinkDto;
export type AuthControllerVerifyMutationError = ApiErrorResponseDto;

/**
 * @summary Verify email token
 */
export const useAuthControllerVerify = <TError = ApiErrorResponseDto, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerVerify>>,
      TError,
      { data: VerifyMagicLinkDto },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerVerify>>,
  TError,
  { data: VerifyMagicLinkDto },
  TContext
> => {
  return useMutation(getAuthControllerVerifyMutationOptions(options), queryClient);
};
/**
 * @summary Request a magic link
 */
export const magicLinkControllerRequest = (
  requestMagicLinkDto: RequestMagicLinkDto,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<MagicLinkControllerRequest200>(
    {
      url: `http://localhost:8000/api/auth/magic-link/request`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: requestMagicLinkDto,
      signal,
    },
    options,
  );
};

export const getMagicLinkControllerRequestMutationOptions = <
  TError = ApiErrorResponseDto,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof magicLinkControllerRequest>>,
    TError,
    { data: RequestMagicLinkDto },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof magicLinkControllerRequest>>,
  TError,
  { data: RequestMagicLinkDto },
  TContext
> => {
  const mutationKey = ["magicLinkControllerRequest"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof magicLinkControllerRequest>>,
    { data: RequestMagicLinkDto }
  > = (props) => {
    const { data } = props ?? {};

    return magicLinkControllerRequest(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MagicLinkControllerRequestMutationResult = NonNullable<
  Awaited<ReturnType<typeof magicLinkControllerRequest>>
>;
export type MagicLinkControllerRequestMutationBody = RequestMagicLinkDto;
export type MagicLinkControllerRequestMutationError = ApiErrorResponseDto;

/**
 * @summary Request a magic link
 */
export const useMagicLinkControllerRequest = <TError = ApiErrorResponseDto, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof magicLinkControllerRequest>>,
      TError,
      { data: RequestMagicLinkDto },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof magicLinkControllerRequest>>,
  TError,
  { data: RequestMagicLinkDto },
  TContext
> => {
  return useMutation(getMagicLinkControllerRequestMutationOptions(options), queryClient);
};
/**
 * @summary Verify a magic link token
 */
export const magicLinkControllerVerify = (
  verifyMagicLinkDto: VerifyMagicLinkDto,
  options?: SecondParameter<typeof api>,
  signal?: AbortSignal,
) => {
  return api<MagicLinkControllerVerify200>(
    {
      url: `http://localhost:8000/api/auth/magic-link/verify`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: verifyMagicLinkDto,
      signal,
    },
    options,
  );
};

export const getMagicLinkControllerVerifyMutationOptions = <
  TError = ApiErrorResponseDto,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof magicLinkControllerVerify>>,
    TError,
    { data: VerifyMagicLinkDto },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof magicLinkControllerVerify>>,
  TError,
  { data: VerifyMagicLinkDto },
  TContext
> => {
  const mutationKey = ["magicLinkControllerVerify"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof magicLinkControllerVerify>>,
    { data: VerifyMagicLinkDto }
  > = (props) => {
    const { data } = props ?? {};

    return magicLinkControllerVerify(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MagicLinkControllerVerifyMutationResult = NonNullable<
  Awaited<ReturnType<typeof magicLinkControllerVerify>>
>;
export type MagicLinkControllerVerifyMutationBody = VerifyMagicLinkDto;
export type MagicLinkControllerVerifyMutationError = ApiErrorResponseDto;

/**
 * @summary Verify a magic link token
 */
export const useMagicLinkControllerVerify = <TError = ApiErrorResponseDto, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof magicLinkControllerVerify>>,
      TError,
      { data: VerifyMagicLinkDto },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof magicLinkControllerVerify>>,
  TError,
  { data: VerifyMagicLinkDto },
  TContext
> => {
  return useMutation(getMagicLinkControllerVerifyMutationOptions(options), queryClient);
};
