/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type {
  AuthControllerGetProfile200,
  AuthControllerLogin200,
  AuthControllerLogout200,
  AuthControllerRegister201,
  AuthControllerResendVerification200,
  AuthControllerVerify200,
  LoginDto,
  MagicLinkControllerRequest200,
  MagicLinkControllerVerify200,
  RegisterDto,
  RequestMagicLinkDto,
  ResendVerificationDto,
  VerifyMagicLinkDto,
} from "../../../../types/api";

import { api } from "../../../apiClient";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getAuth = () => {
  /**
   * @summary Login with email and password
   */
  const authControllerLogin = (
    loginDto: LoginDto,
    options?: SecondParameter<typeof api<AuthControllerLogin200>>,
  ) => {
    return api<AuthControllerLogin200>(
      {
        url: `http://localhost:8000/api/auth/login`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: loginDto,
      },
      options,
    );
  };
  /**
   * @summary Logout the current user
   */
  const authControllerLogout = (options?: SecondParameter<typeof api<AuthControllerLogout200>>) => {
    return api<AuthControllerLogout200>(
      { url: `http://localhost:8000/api/auth/logout`, method: "POST" },
      options,
    );
  };
  /**
   * @summary Get current user profile
   */
  const authControllerGetProfile = (
    options?: SecondParameter<typeof api<AuthControllerGetProfile200>>,
  ) => {
    return api<AuthControllerGetProfile200>(
      { url: `http://localhost:8000/api/auth/me`, method: "GET" },
      options,
    );
  };
  /**
   * @summary Register a new user
   */
  const authControllerRegister = (
    registerDto: RegisterDto,
    options?: SecondParameter<typeof api<AuthControllerRegister201>>,
  ) => {
    return api<AuthControllerRegister201>(
      {
        url: `http://localhost:8000/api/auth/register`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: registerDto,
      },
      options,
    );
  };
  /**
   * @summary Resend verification email
   */
  const authControllerResendVerification = (
    resendVerificationDto: ResendVerificationDto,
    options?: SecondParameter<typeof api<AuthControllerResendVerification200>>,
  ) => {
    return api<AuthControllerResendVerification200>(
      {
        url: `http://localhost:8000/api/auth/resend-verification`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: resendVerificationDto,
      },
      options,
    );
  };
  /**
   * @summary Login with Google OAuth2
   */
  const authControllerGoogleAuth = (options?: SecondParameter<typeof api<void>>) => {
    return api<void>({ url: `http://localhost:8000/api/auth/google`, method: "GET" }, options);
  };
  /**
   * @summary Google OAuth2 callback
   */
  const authControllerGoogleAuthRedirect = (options?: SecondParameter<typeof api<void>>) => {
    return api<void>(
      { url: `http://localhost:8000/api/auth/google/callback`, method: "GET" },
      options,
    );
  };
  /**
   * @summary Verify email token
   */
  const authControllerVerify = (
    verifyMagicLinkDto: VerifyMagicLinkDto,
    options?: SecondParameter<typeof api<AuthControllerVerify200>>,
  ) => {
    return api<AuthControllerVerify200>(
      {
        url: `http://localhost:8000/api/auth/verify`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: verifyMagicLinkDto,
      },
      options,
    );
  };
  /**
   * @summary Request a magic link
   */
  const magicLinkControllerRequest = (
    requestMagicLinkDto: RequestMagicLinkDto,
    options?: SecondParameter<typeof api<MagicLinkControllerRequest200>>,
  ) => {
    return api<MagicLinkControllerRequest200>(
      {
        url: `http://localhost:8000/api/auth/magic-link/request`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: requestMagicLinkDto,
      },
      options,
    );
  };
  /**
   * @summary Verify a magic link token
   */
  const magicLinkControllerVerify = (
    verifyMagicLinkDto: VerifyMagicLinkDto,
    options?: SecondParameter<typeof api<MagicLinkControllerVerify200>>,
  ) => {
    return api<MagicLinkControllerVerify200>(
      {
        url: `http://localhost:8000/api/auth/magic-link/verify`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: verifyMagicLinkDto,
      },
      options,
    );
  };
  return {
    authControllerLogin,
    authControllerLogout,
    authControllerGetProfile,
    authControllerRegister,
    authControllerResendVerification,
    authControllerGoogleAuth,
    authControllerGoogleAuthRedirect,
    authControllerVerify,
    magicLinkControllerRequest,
    magicLinkControllerVerify,
  };
};
export type AuthControllerLoginResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["authControllerLogin"]>>
>;
export type AuthControllerLogoutResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["authControllerLogout"]>>
>;
export type AuthControllerGetProfileResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["authControllerGetProfile"]>>
>;
export type AuthControllerRegisterResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["authControllerRegister"]>>
>;
export type AuthControllerResendVerificationResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["authControllerResendVerification"]>>
>;
export type AuthControllerGoogleAuthResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["authControllerGoogleAuth"]>>
>;
export type AuthControllerGoogleAuthRedirectResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["authControllerGoogleAuthRedirect"]>>
>;
export type AuthControllerVerifyResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["authControllerVerify"]>>
>;
export type MagicLinkControllerRequestResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["magicLinkControllerRequest"]>>
>;
export type MagicLinkControllerVerifyResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["magicLinkControllerVerify"]>>
>;
