/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { ApiErrorResponseDtoStatusCode } from "./apiErrorResponseDtoStatusCode";

export interface ApiErrorResponseDto {
  /** The HTTP status code */
  statusCode: ApiErrorResponseDtoStatusCode;
  /** The timestamp of the error in ISO 8601 format */
  timestamp: string;
  /** The path where the error occurred */
  path: string;
  /** The error message or an array of validation error messages */
  message: string | string[];
}
