/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

/**
 * The HTTP status code
 */
export type ApiErrorResponseDtoStatusCode =
  (typeof ApiErrorResponseDtoStatusCode)[keyof typeof ApiErrorResponseDtoStatusCode];

export const ApiErrorResponseDtoStatusCode = {
  NUMBER_400: 400,
  NUMBER_401: 401,
  NUMBER_403: 403,
  NUMBER_404: 404,
  NUMBER_429: 429,
  NUMBER_500: 500,
} as const;
