/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { MessageResponseDto } from "./messageResponseDto";
import type { SuccessResponseDto } from "./successResponseDto";

export type AuthControllerLogout200 = SuccessResponseDto & {
  statusCode: number;
  message: string;
  data: MessageResponseDto;
};
