/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export interface LoginDto {
  /** The email address of the user */
  email: string;
  /**
   * The password of the user
   * @minLength 8
   */
  password: string;
}
