/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export interface MessageResponseDto {
  /** A message describing the result of the operation */
  message: string;
}
