/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

export interface RegisterDto {
  /** The email address of the user */
  email: string;
  /**
   * The password of the user (8-32 characters)
   * @minLength 8
   * @maxLength 32
   */
  password: string;
  /** The first name of the user */
  firstName?: string;
  /** The last name of the user */
  lastName?: string;
}
