/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */
import type { SuccessResponseDtoData } from "./successResponseDtoData";

export interface SuccessResponseDto {
  /** The HTTP status code */
  statusCode: number;
  /** The success message */
  message: string;
  /** The actual response data */
  data: SuccessResponseDtoData;
}
