/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: 1.0
 */

/**
 * The actual response data
 */
export type SuccessResponseDtoData = { [key: string]: unknown };
